// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_0_v_demosaic_0_0_AXIvideo2MultiBayer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        imgBayer_din,
        imgBayer_full_n,
        imgBayer_write,
        Height,
        WidthIn
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input  [3:0] s_axis_video_TKEEP;
input  [3:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output  [31:0] imgBayer_din;
input   imgBayer_full_n;
output   imgBayer_write;
input  [15:0] Height;
input  [15:0] WidthIn;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg imgBayer_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] trunc_ln_reg_409;
wire    ap_CS_fsm_state2;
wire   [11:0] grp_reg_unsigned_short_s_fu_278_ap_return;
reg   [11:0] rows_reg_415;
wire    ap_CS_fsm_state4;
wire   [0:0] cmp7233_fu_289_p2;
reg   [0:0] cmp7233_reg_423;
wire   [11:0] i_2_fu_311_p2;
reg   [11:0] i_2_reg_433;
wire    ap_CS_fsm_state5;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_start;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_done;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_idle;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_ready;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_s_axis_video_TREADY;
wire   [31:0] grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_axi_data_V_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_axi_data_V_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_axi_last_V_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_axi_last_V_out_ap_vld;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_start;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_done;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_idle;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_ready;
wire   [31:0] grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_imgBayer_din;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_imgBayer_write;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_s_axis_video_TREADY;
wire   [0:0] grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_eol_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_eol_out_ap_vld;
wire   [31:0] grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_axi_data_V_3_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_axi_data_V_3_out_ap_vld;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_start;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_done;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_idle;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_ready;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_s_axis_video_TREADY;
wire   [31:0] grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_axi_data_V_4_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_axi_data_V_4_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_axi_last_V_4_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_axi_last_V_4_out_ap_vld;
wire   [11:0] grp_reg_unsigned_short_s_fu_252_d;
wire   [11:0] grp_reg_unsigned_short_s_fu_252_ap_return;
wire   [11:0] grp_reg_unsigned_short_s_fu_278_d;
reg   [0:0] axi_last_V_2_reg_128;
wire    ap_CS_fsm_state10;
reg   [31:0] axi_0_2_lcssa_reg_138;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln114_fu_306_p2;
reg   [0:0] axi_4_2_lcssa_reg_148;
reg   [0:0] eol_0_lcssa_reg_159;
reg    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [0:0] axi_last_V_4_loc_fu_92;
reg   [11:0] i_fu_80;
reg    ap_block_state1;
reg   [31:0] axi_data_V_2_fu_84;
reg   [0:0] sof_fu_88;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    regslice_both_s_axis_video_V_data_V_U_apdone_blk;
wire   [31:0] s_axis_video_TDATA_int_regslice;
wire    s_axis_video_TVALID_int_regslice;
reg    s_axis_video_TREADY_int_regslice;
wire    regslice_both_s_axis_video_V_data_V_U_ack_in;
wire    regslice_both_s_axis_video_V_keep_V_U_apdone_blk;
wire   [3:0] s_axis_video_TKEEP_int_regslice;
wire    regslice_both_s_axis_video_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_video_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_video_V_strb_V_U_apdone_blk;
wire   [3:0] s_axis_video_TSTRB_int_regslice;
wire    regslice_both_s_axis_video_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_video_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_video_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_video_TUSER_int_regslice;
wire    regslice_both_s_axis_video_V_user_V_U_vld_out;
wire    regslice_both_s_axis_video_V_user_V_U_ack_in;
wire    regslice_both_s_axis_video_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_video_TLAST_int_regslice;
wire    regslice_both_s_axis_video_V_last_V_U_vld_out;
wire    regslice_both_s_axis_video_V_last_V_U_ack_in;
wire    regslice_both_s_axis_video_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_video_TID_int_regslice;
wire    regslice_both_s_axis_video_V_id_V_U_vld_out;
wire    regslice_both_s_axis_video_V_id_V_U_ack_in;
wire    regslice_both_s_axis_video_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_video_TDEST_int_regslice;
wire    regslice_both_s_axis_video_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_video_V_dest_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_start_reg = 1'b0;
end

design_0_v_demosaic_0_0_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_start),
    .ap_done(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_done),
    .ap_idle(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_idle),
    .ap_ready(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .axi_data_V_out(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_axi_data_V_out),
    .axi_data_V_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_axi_data_V_out_ap_vld),
    .axi_last_V_out(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_axi_last_V_out),
    .axi_last_V_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_axi_last_V_out_ap_vld)
);

design_0_v_demosaic_0_0_AXIvideo2MultiBayer_Pipeline_loop_width grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_start),
    .ap_done(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_done),
    .ap_idle(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_idle),
    .ap_ready(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .imgBayer_din(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_imgBayer_din),
    .imgBayer_full_n(imgBayer_full_n),
    .imgBayer_write(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_imgBayer_write),
    .sof_5(sof_fu_88),
    .axi_last_V_2(axi_last_V_2_reg_128),
    .axi_data_V_2(axi_data_V_2_fu_84),
    .trunc_ln18(trunc_ln_reg_409),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .eol_out(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_eol_out),
    .eol_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_eol_out_ap_vld),
    .axi_data_V_3_out(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_axi_data_V_3_out),
    .axi_data_V_3_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_axi_data_V_3_out_ap_vld)
);

design_0_v_demosaic_0_0_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_start),
    .ap_done(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_done),
    .ap_idle(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_idle),
    .ap_ready(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .axi_0_2_lcssa(axi_0_2_lcssa_reg_138),
    .axi_4_2_lcssa(axi_4_2_lcssa_reg_148),
    .eol_0_lcssa(eol_0_lcssa_reg_159),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .axi_data_V_4_out(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_axi_data_V_4_out),
    .axi_data_V_4_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_axi_data_V_4_out_ap_vld),
    .axi_last_V_4_out(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_axi_last_V_4_out),
    .axi_last_V_4_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_axi_last_V_4_out_ap_vld)
);

design_0_v_demosaic_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_252(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(grp_reg_unsigned_short_s_fu_252_d),
    .ap_return(grp_reg_unsigned_short_s_fu_252_ap_return)
);

design_0_v_demosaic_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_278(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(grp_reg_unsigned_short_s_fu_278_d),
    .ap_return(grp_reg_unsigned_short_s_fu_278_ap_return)
);

design_0_v_demosaic_0_0_regslice_both #(
    .DataWidth( 32 ))
regslice_both_s_axis_video_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TDATA),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_data_V_U_ack_in),
    .data_out(s_axis_video_TDATA_int_regslice),
    .vld_out(s_axis_video_TVALID_int_regslice),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_data_V_U_apdone_blk)
);

design_0_v_demosaic_0_0_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_axis_video_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TKEEP),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_keep_V_U_ack_in),
    .data_out(s_axis_video_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_keep_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_keep_V_U_apdone_blk)
);

design_0_v_demosaic_0_0_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_axis_video_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TSTRB),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_strb_V_U_ack_in),
    .data_out(s_axis_video_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_strb_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_strb_V_U_apdone_blk)
);

design_0_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TUSER),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_user_V_U_ack_in),
    .data_out(s_axis_video_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_user_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_user_V_U_apdone_blk)
);

design_0_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TLAST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_last_V_U_ack_in),
    .data_out(s_axis_video_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_last_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_last_V_U_apdone_blk)
);

design_0_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TID),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_id_V_U_ack_in),
    .data_out(s_axis_video_TID_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_id_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_id_V_U_apdone_blk)
);

design_0_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TDEST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_dest_V_U_ack_in),
    .data_out(s_axis_video_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_dest_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln114_fu_306_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_start_reg <= 1'b0;
    end else begin
        if (((cmp7233_reg_423 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln114_fu_306_p2 == 1'd0))) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((cmp7233_reg_423 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln114_fu_306_p2 == 1'd0))) begin
        axi_0_2_lcssa_reg_138 <= axi_data_V_2_fu_84;
    end else if (((cmp7233_reg_423 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        axi_0_2_lcssa_reg_138 <= grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_axi_data_V_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp7233_reg_423 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln114_fu_306_p2 == 1'd0))) begin
        axi_4_2_lcssa_reg_148 <= axi_last_V_2_reg_128;
    end else if (((cmp7233_reg_423 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        axi_4_2_lcssa_reg_148 <= grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_eol_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_data_V_2_fu_84 <= grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_axi_data_V_out;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        axi_data_V_2_fu_84 <= grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_axi_data_V_4_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        axi_last_V_2_reg_128 <= axi_last_V_4_loc_fu_92;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_last_V_2_reg_128 <= grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_axi_last_V_out;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp7233_reg_423 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln114_fu_306_p2 == 1'd0))) begin
        eol_0_lcssa_reg_159 <= 1'd0;
    end else if (((cmp7233_reg_423 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        eol_0_lcssa_reg_159 <= grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_eol_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_80 <= 12'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        i_fu_80 <= i_2_reg_433;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        sof_fu_88 <= 1'd1;
    end else if (((cmp7233_reg_423 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        sof_fu_88 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_axi_last_V_4_out_ap_vld == 1'b1))) begin
        axi_last_V_4_loc_fu_92 <= grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_axi_last_V_4_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cmp7233_reg_423 <= cmp7233_fu_289_p2;
        rows_reg_415 <= grp_reg_unsigned_short_s_fu_278_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_2_reg_433 <= i_2_fu_311_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln_reg_409 <= {{grp_reg_unsigned_short_s_fu_252_ap_return[11:2]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln114_fu_306_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln114_fu_306_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        imgBayer_write = grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_imgBayer_write;
    end else begin
        imgBayer_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_s_axis_video_TREADY;
    end else begin
        s_axis_video_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln114_fu_306_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((cmp7233_reg_423 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln114_fu_306_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign cmp7233_fu_289_p2 = ((trunc_ln_reg_409 == 10'd0) ? 1'b1 : 1'b0);

assign grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_start = grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_218_ap_start_reg;

assign grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_start = grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_171_ap_start_reg;

assign grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_start = grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_ap_start_reg;

assign grp_reg_unsigned_short_s_fu_252_d = WidthIn[11:0];

assign grp_reg_unsigned_short_s_fu_278_d = Height[11:0];

assign i_2_fu_311_p2 = (i_fu_80 + 12'd1);

assign icmp_ln114_fu_306_p2 = ((i_fu_80 == rows_reg_415) ? 1'b1 : 1'b0);

assign imgBayer_din = grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_191_imgBayer_din;

assign s_axis_video_TREADY = regslice_both_s_axis_video_V_data_V_U_ack_in;

endmodule //design_0_v_demosaic_0_0_AXIvideo2MultiBayer
