// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_0_v_demosaic_0_0_DebayerRatBorBatR (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        imgG_dout,
        imgG_empty_n,
        imgG_read,
        imgRB_din,
        imgRB_full_n,
        imgRB_write,
        height,
        width,
        bayerPhase_c9_dout,
        bayerPhase_c9_empty_n,
        bayerPhase_c9_read,
        bayerPhase_c_din,
        bayerPhase_c_full_n,
        bayerPhase_c_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [95:0] imgG_dout;
input   imgG_empty_n;
output   imgG_read;
output  [95:0] imgRB_din;
input   imgRB_full_n;
output   imgRB_write;
input  [11:0] height;
input  [11:0] width;
input  [15:0] bayerPhase_c9_dout;
input   bayerPhase_c9_empty_n;
output   bayerPhase_c9_read;
output  [15:0] bayerPhase_c_din;
input   bayerPhase_c_full_n;
output   bayerPhase_c_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg imgG_read;
reg imgRB_write;
reg bayerPhase_c9_read;
reg bayerPhase_c_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    bayerPhase_c9_blk_n;
reg    bayerPhase_c_blk_n;
wire   [11:0] loopHeight_fu_918_p2;
reg   [14:0] trunc_ln574_1_i_reg_2971;
wire   [14:0] zext_ln575_fu_938_p1;
reg   [14:0] zext_ln575_reg_2977;
wire   [14:0] zext_ln724_fu_970_p1;
reg   [14:0] zext_ln724_reg_2987;
wire   [12:0] out_y_i_fu_1313_p2;
reg   [12:0] out_y_i_reg_3229;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln582_fu_986_p2;
wire   [0:0] red_i_fu_1335_p2;
reg   [0:0] red_i_reg_3234;
wire   [1:0] idxprom238_t_i_fu_1341_p3;
reg   [1:0] idxprom238_t_i_reg_3239;
wire   [1:0] idxprom369_t_i_fu_1350_p3;
reg   [1:0] idxprom369_t_i_reg_3244;
wire   [0:0] cmp37_i_fu_1359_p2;
reg   [0:0] cmp37_i_reg_3249;
wire   [0:0] cmp140_i_fu_1365_p2;
reg   [0:0] cmp140_i_reg_3254;
wire   [0:0] icmp_ln724_fu_1372_p2;
reg   [0:0] icmp_ln724_reg_3259;
wire   [0:0] icmp_ln724_1_fu_1378_p2;
reg   [0:0] icmp_ln724_1_reg_3264;
wire   [95:0] lineBuffer_val_V_0_q1;
wire   [95:0] lineBuffer_val_V_1_q1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_start;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_done;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_idle;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_ready;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_imgG_read;
wire   [95:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_imgRB_din;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_imgRB_write;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_add_ln582_1_i;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_address0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_ce0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_we0;
wire   [95:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_d0;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_address1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_ce1;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_address0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_ce0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_we0;
wire   [95:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_d0;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_address1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_ce1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_red_i;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_11_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_11_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_10_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_10_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_9_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_9_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_8_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_8_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_7_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_7_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_6_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_6_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_5_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_5_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_4_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_4_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_3_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_3_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_2_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_0_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_11_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_11_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_10_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_10_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_9_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_9_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_8_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_8_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_7_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_7_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_6_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_6_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_5_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_5_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_4_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_4_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_3_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_3_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_2_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_0_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_11_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_11_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_10_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_10_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_9_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_9_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_8_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_8_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_7_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_7_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_6_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_6_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_5_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_5_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_4_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_4_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_3_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_3_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_2_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_0_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_2_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_0_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_2_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_0_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_2_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_0_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_2_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_0_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_2_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_0_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_2_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_0_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_2_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_0_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_2_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_0_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_2_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_0_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_2_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_0_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_2_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_0_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_2_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_0_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_2_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_0_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_2_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_0_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_0_i_out_ap_vld;
reg    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [11:0] y_fu_80;
wire   [11:0] y_4_fu_991_p2;
reg    ap_block_state1;
reg   [7:0] pixWindow_val_val_V_0_4_0_0_i_fu_84;
wire    ap_CS_fsm_state4;
reg   [7:0] pixWindow_val_val_V_0_4_1_0_i_fu_88;
reg   [7:0] pixWindow_val_val_V_0_4_2_0_i_fu_92;
reg   [7:0] pixWindow_val_val_V_0_5_0_0_i_fu_96;
reg   [7:0] pixWindow_val_val_V_0_5_1_0_i_fu_100;
reg   [7:0] pixWindow_val_val_V_0_5_2_0_i_fu_104;
reg   [7:0] pixWindow_val_val_V_0_6_0_0_i_fu_108;
reg   [7:0] pixWindow_val_val_V_0_6_1_0_i_fu_112;
reg   [7:0] pixWindow_val_val_V_0_6_2_0_i_fu_116;
reg   [7:0] pixWindow_val_val_V_0_7_0_0_i_fu_120;
reg   [7:0] pixWindow_val_val_V_0_7_1_0_i_fu_124;
reg   [7:0] pixWindow_val_val_V_0_7_2_0_i_fu_128;
reg   [7:0] pixWindow_val_val_V_0_8_0_0_i_fu_132;
reg   [7:0] pixWindow_val_val_V_0_8_1_0_i_fu_136;
reg   [7:0] pixWindow_val_val_V_0_8_2_0_i_fu_140;
reg   [7:0] pixWindow_val_val_V_1_5_0_0_i_fu_144;
reg   [7:0] pixWindow_val_val_V_1_5_1_0_i_fu_148;
reg   [7:0] pixWindow_val_val_V_1_5_2_0_i_fu_152;
reg   [7:0] pixWindow_val_val_V_1_6_0_0_i_fu_156;
reg   [7:0] pixWindow_val_val_V_1_6_1_0_i_fu_160;
reg   [7:0] pixWindow_val_val_V_1_6_2_0_i_fu_164;
reg   [7:0] pixWindow_val_val_V_1_7_0_0_i_fu_168;
reg   [7:0] pixWindow_val_val_V_1_7_1_0_i_fu_172;
reg   [7:0] pixWindow_val_val_V_1_7_2_0_i_fu_176;
reg   [7:0] pixWindow_val_val_V_1_8_0_0_i_fu_180;
reg   [7:0] pixWindow_val_val_V_1_8_1_0_i_fu_184;
reg   [7:0] pixWindow_val_val_V_1_8_2_0_i_fu_188;
reg   [7:0] pixWindow_val_val_V_2_4_0_0_i_fu_192;
reg   [7:0] pixWindow_val_val_V_2_4_1_0_i_fu_196;
reg   [7:0] pixWindow_val_val_V_2_4_2_0_i_fu_200;
reg   [7:0] pixWindow_val_val_V_2_5_0_0_i_fu_204;
reg   [7:0] pixWindow_val_val_V_2_5_1_0_i_fu_208;
reg   [7:0] pixWindow_val_val_V_2_5_2_0_i_fu_212;
reg   [7:0] pixWindow_val_val_V_2_6_0_0_i_fu_216;
reg   [7:0] pixWindow_val_val_V_2_6_1_0_i_fu_220;
reg   [7:0] pixWindow_val_val_V_2_6_2_0_i_fu_224;
reg   [7:0] pixWindow_val_val_V_2_7_0_0_i_fu_228;
reg   [7:0] pixWindow_val_val_V_2_7_1_0_i_fu_232;
reg   [7:0] pixWindow_val_val_V_2_7_2_0_i_fu_236;
reg   [7:0] pixWindow_val_val_V_2_8_0_0_i_fu_240;
reg   [7:0] pixWindow_val_val_V_2_8_1_0_i_fu_244;
reg   [7:0] pixWindow_val_val_V_2_8_2_0_i_fu_248;
reg   [7:0] pixBuf_val_V_0_0_0_i_fu_252;
reg   [7:0] pixBuf_val_V_0_1_0_i_fu_256;
reg   [7:0] pixBuf_val_V_0_2_0_i_fu_260;
reg   [7:0] pixBuf_val_V_0_3_0_i_fu_264;
reg   [7:0] pixBuf_val_V_0_4_0_i_fu_268;
reg   [7:0] pixBuf_val_V_0_5_0_i_fu_272;
reg   [7:0] pixBuf_val_V_0_6_0_i_fu_276;
reg   [7:0] pixBuf_val_V_0_7_0_i_fu_280;
reg   [7:0] pixBuf_val_V_0_8_0_i_fu_284;
reg   [7:0] pixBuf_val_V_0_9_0_i_fu_288;
reg   [7:0] pixBuf_val_V_0_10_0_i_fu_292;
reg   [7:0] pixBuf_val_V_0_11_0_i_fu_296;
reg   [7:0] pixBuf_val_V_1_0_03224_i_fu_300;
reg   [7:0] pixBuf_val_V_1_1_03225_i_fu_304;
reg   [7:0] pixBuf_val_V_1_2_03226_i_fu_308;
reg   [7:0] pixBuf_val_V_1_3_03227_i_fu_312;
reg   [7:0] pixBuf_val_V_1_4_03228_i_fu_316;
reg   [7:0] pixBuf_val_V_1_5_03229_i_fu_320;
reg   [7:0] pixBuf_val_V_1_6_03230_i_fu_324;
reg   [7:0] pixBuf_val_V_1_7_03231_i_fu_328;
reg   [7:0] pixBuf_val_V_1_8_03232_i_fu_332;
reg   [7:0] pixBuf_val_V_1_9_03233_i_fu_336;
reg   [7:0] pixBuf_val_V_1_10_03234_i_fu_340;
reg   [7:0] pixBuf_val_V_1_11_03235_i_fu_344;
reg   [7:0] pixBuf_val_V_2_0_03236_i_fu_348;
reg   [7:0] pixBuf_val_V_2_1_03237_i_fu_352;
reg   [7:0] pixBuf_val_V_2_2_03238_i_fu_356;
reg   [7:0] pixBuf_val_V_2_3_03239_i_fu_360;
reg   [7:0] pixBuf_val_V_2_4_03240_i_fu_364;
reg   [7:0] pixBuf_val_V_2_5_03241_i_fu_368;
reg   [7:0] pixBuf_val_V_2_6_03242_i_fu_372;
reg   [7:0] pixBuf_val_V_2_7_03243_i_fu_376;
reg   [7:0] pixBuf_val_V_2_8_03244_i_fu_380;
reg   [7:0] pixBuf_val_V_2_9_03245_i_fu_384;
reg   [7:0] pixBuf_val_V_2_10_03246_i_fu_388;
reg   [7:0] pixBuf_val_V_2_11_03247_i_fu_392;
wire   [0:0] x_phase_fu_924_p1;
wire   [11:0] add_ln582_fu_942_p2;
wire   [9:0] trunc_ln_i_fu_948_p4;
wire   [0:0] xor_ln724_fu_964_p2;
wire   [12:0] zext_ln582_fu_982_p1;
wire   [0:0] empty_182_fu_1309_p1;
wire   [0:0] out_y_cast_i_fu_1320_p2;
wire   [14:0] and219_cast_i_fu_1326_p1;
wire   [14:0] xor_i_fu_1330_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_start_reg = 1'b0;
end

design_0_v_demosaic_0_0_DebayerRatBorBatR_lineBuffer_val_V_0 #(
    .DataWidth( 96 ),
    .AddressRange( 961 ),
    .AddressWidth( 10 ))
lineBuffer_val_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_address0),
    .ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_ce0),
    .we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_we0),
    .d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_d0),
    .address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_address1),
    .ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_ce1),
    .q1(lineBuffer_val_V_0_q1)
);

design_0_v_demosaic_0_0_DebayerRatBorBatR_lineBuffer_val_V_0 #(
    .DataWidth( 96 ),
    .AddressRange( 961 ),
    .AddressWidth( 10 ))
lineBuffer_val_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_address0),
    .ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_ce0),
    .we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_we0),
    .d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_d0),
    .address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_address1),
    .ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_ce1),
    .q1(lineBuffer_val_V_1_q1)
);

design_0_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2 grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_start),
    .ap_done(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_done),
    .ap_idle(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_idle),
    .ap_ready(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_ready),
    .imgG_dout(imgG_dout),
    .imgG_empty_n(imgG_empty_n),
    .imgG_read(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_imgG_read),
    .imgRB_din(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_imgRB_din),
    .imgRB_full_n(imgRB_full_n),
    .imgRB_write(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_imgRB_write),
    .pixBuf_val_V_2_11_03247_i(pixBuf_val_V_2_11_03247_i_fu_392),
    .pixBuf_val_V_2_10_03246_i(pixBuf_val_V_2_10_03246_i_fu_388),
    .pixBuf_val_V_2_9_03245_i(pixBuf_val_V_2_9_03245_i_fu_384),
    .pixBuf_val_V_2_8_03244_i(pixBuf_val_V_2_8_03244_i_fu_380),
    .pixBuf_val_V_2_7_03243_i(pixBuf_val_V_2_7_03243_i_fu_376),
    .pixBuf_val_V_2_6_03242_i(pixBuf_val_V_2_6_03242_i_fu_372),
    .pixBuf_val_V_2_5_03241_i(pixBuf_val_V_2_5_03241_i_fu_368),
    .pixBuf_val_V_2_4_03240_i(pixBuf_val_V_2_4_03240_i_fu_364),
    .pixBuf_val_V_2_3_03239_i(pixBuf_val_V_2_3_03239_i_fu_360),
    .pixBuf_val_V_2_2_03238_i(pixBuf_val_V_2_2_03238_i_fu_356),
    .pixBuf_val_V_2_1_03237_i(pixBuf_val_V_2_1_03237_i_fu_352),
    .pixBuf_val_V_2_0_03236_i(pixBuf_val_V_2_0_03236_i_fu_348),
    .pixBuf_val_V_1_11_03235_i(pixBuf_val_V_1_11_03235_i_fu_344),
    .pixBuf_val_V_1_10_03234_i(pixBuf_val_V_1_10_03234_i_fu_340),
    .pixBuf_val_V_1_9_03233_i(pixBuf_val_V_1_9_03233_i_fu_336),
    .pixBuf_val_V_1_8_03232_i(pixBuf_val_V_1_8_03232_i_fu_332),
    .pixBuf_val_V_1_7_03231_i(pixBuf_val_V_1_7_03231_i_fu_328),
    .pixBuf_val_V_1_6_03230_i(pixBuf_val_V_1_6_03230_i_fu_324),
    .pixBuf_val_V_1_5_03229_i(pixBuf_val_V_1_5_03229_i_fu_320),
    .pixBuf_val_V_1_4_03228_i(pixBuf_val_V_1_4_03228_i_fu_316),
    .pixBuf_val_V_1_3_03227_i(pixBuf_val_V_1_3_03227_i_fu_312),
    .pixBuf_val_V_1_2_03226_i(pixBuf_val_V_1_2_03226_i_fu_308),
    .pixBuf_val_V_1_1_03225_i(pixBuf_val_V_1_1_03225_i_fu_304),
    .pixBuf_val_V_1_0_03224_i(pixBuf_val_V_1_0_03224_i_fu_300),
    .pixBuf_val_V_0_11_0_i(pixBuf_val_V_0_11_0_i_fu_296),
    .pixBuf_val_V_0_10_0_i(pixBuf_val_V_0_10_0_i_fu_292),
    .pixBuf_val_V_0_9_0_i(pixBuf_val_V_0_9_0_i_fu_288),
    .pixBuf_val_V_0_8_0_i(pixBuf_val_V_0_8_0_i_fu_284),
    .pixBuf_val_V_0_7_0_i(pixBuf_val_V_0_7_0_i_fu_280),
    .pixBuf_val_V_0_6_0_i(pixBuf_val_V_0_6_0_i_fu_276),
    .pixBuf_val_V_0_5_0_i(pixBuf_val_V_0_5_0_i_fu_272),
    .pixBuf_val_V_0_4_0_i(pixBuf_val_V_0_4_0_i_fu_268),
    .pixBuf_val_V_0_3_0_i(pixBuf_val_V_0_3_0_i_fu_264),
    .pixBuf_val_V_0_2_0_i(pixBuf_val_V_0_2_0_i_fu_260),
    .pixBuf_val_V_0_1_0_i(pixBuf_val_V_0_1_0_i_fu_256),
    .pixBuf_val_V_0_0_0_i(pixBuf_val_V_0_0_0_i_fu_252),
    .pixWindow_val_val_V_2_8_2_0_i(pixWindow_val_val_V_2_8_2_0_i_fu_248),
    .pixWindow_val_val_V_2_8_1_0_i(pixWindow_val_val_V_2_8_1_0_i_fu_244),
    .pixWindow_val_val_V_2_8_0_0_i(pixWindow_val_val_V_2_8_0_0_i_fu_240),
    .pixWindow_val_val_V_2_7_2_0_i(pixWindow_val_val_V_2_7_2_0_i_fu_236),
    .pixWindow_val_val_V_2_7_1_0_i(pixWindow_val_val_V_2_7_1_0_i_fu_232),
    .pixWindow_val_val_V_2_7_0_0_i(pixWindow_val_val_V_2_7_0_0_i_fu_228),
    .pixWindow_val_val_V_2_6_2_0_i(pixWindow_val_val_V_2_6_2_0_i_fu_224),
    .pixWindow_val_val_V_2_6_1_0_i(pixWindow_val_val_V_2_6_1_0_i_fu_220),
    .pixWindow_val_val_V_2_6_0_0_i(pixWindow_val_val_V_2_6_0_0_i_fu_216),
    .pixWindow_val_val_V_2_5_2_0_i(pixWindow_val_val_V_2_5_2_0_i_fu_212),
    .pixWindow_val_val_V_2_5_1_0_i(pixWindow_val_val_V_2_5_1_0_i_fu_208),
    .pixWindow_val_val_V_2_5_0_0_i(pixWindow_val_val_V_2_5_0_0_i_fu_204),
    .pixWindow_val_val_V_2_4_2_0_i(pixWindow_val_val_V_2_4_2_0_i_fu_200),
    .pixWindow_val_val_V_2_4_1_0_i(pixWindow_val_val_V_2_4_1_0_i_fu_196),
    .pixWindow_val_val_V_2_4_0_0_i(pixWindow_val_val_V_2_4_0_0_i_fu_192),
    .pixWindow_val_val_V_1_8_2_0_i(pixWindow_val_val_V_1_8_2_0_i_fu_188),
    .pixWindow_val_val_V_1_8_1_0_i(pixWindow_val_val_V_1_8_1_0_i_fu_184),
    .pixWindow_val_val_V_1_8_0_0_i(pixWindow_val_val_V_1_8_0_0_i_fu_180),
    .pixWindow_val_val_V_1_7_2_0_i(pixWindow_val_val_V_1_7_2_0_i_fu_176),
    .pixWindow_val_val_V_1_7_1_0_i(pixWindow_val_val_V_1_7_1_0_i_fu_172),
    .pixWindow_val_val_V_1_7_0_0_i(pixWindow_val_val_V_1_7_0_0_i_fu_168),
    .pixWindow_val_val_V_1_6_2_0_i(pixWindow_val_val_V_1_6_2_0_i_fu_164),
    .pixWindow_val_val_V_1_6_1_0_i(pixWindow_val_val_V_1_6_1_0_i_fu_160),
    .pixWindow_val_val_V_1_6_0_0_i(pixWindow_val_val_V_1_6_0_0_i_fu_156),
    .pixWindow_val_val_V_1_5_2_0_i(pixWindow_val_val_V_1_5_2_0_i_fu_152),
    .pixWindow_val_val_V_1_5_1_0_i(pixWindow_val_val_V_1_5_1_0_i_fu_148),
    .pixWindow_val_val_V_1_5_0_0_i(pixWindow_val_val_V_1_5_0_0_i_fu_144),
    .pixWindow_val_val_V_0_8_2_0_i(pixWindow_val_val_V_0_8_2_0_i_fu_140),
    .pixWindow_val_val_V_0_8_1_0_i(pixWindow_val_val_V_0_8_1_0_i_fu_136),
    .pixWindow_val_val_V_0_8_0_0_i(pixWindow_val_val_V_0_8_0_0_i_fu_132),
    .pixWindow_val_val_V_0_7_2_0_i(pixWindow_val_val_V_0_7_2_0_i_fu_128),
    .pixWindow_val_val_V_0_7_1_0_i(pixWindow_val_val_V_0_7_1_0_i_fu_124),
    .pixWindow_val_val_V_0_7_0_0_i(pixWindow_val_val_V_0_7_0_0_i_fu_120),
    .pixWindow_val_val_V_0_6_2_0_i(pixWindow_val_val_V_0_6_2_0_i_fu_116),
    .pixWindow_val_val_V_0_6_1_0_i(pixWindow_val_val_V_0_6_1_0_i_fu_112),
    .pixWindow_val_val_V_0_6_0_0_i(pixWindow_val_val_V_0_6_0_0_i_fu_108),
    .pixWindow_val_val_V_0_5_2_0_i(pixWindow_val_val_V_0_5_2_0_i_fu_104),
    .pixWindow_val_val_V_0_5_1_0_i(pixWindow_val_val_V_0_5_1_0_i_fu_100),
    .pixWindow_val_val_V_0_5_0_0_i(pixWindow_val_val_V_0_5_0_0_i_fu_96),
    .pixWindow_val_val_V_0_4_2_0_i(pixWindow_val_val_V_0_4_2_0_i_fu_92),
    .pixWindow_val_val_V_0_4_1_0_i(pixWindow_val_val_V_0_4_1_0_i_fu_88),
    .pixWindow_val_val_V_0_4_0_0_i(pixWindow_val_val_V_0_4_0_0_i_fu_84),
    .add_ln582_1_i(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_add_ln582_1_i),
    .out_y_i(out_y_i_reg_3229),
    .icmp_ln724_1_i(icmp_ln724_1_reg_3264),
    .icmp_ln724_i(icmp_ln724_reg_3259),
    .width_cast(width),
    .lineBuffer_val_V_0_i_address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_address0),
    .lineBuffer_val_V_0_i_ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_ce0),
    .lineBuffer_val_V_0_i_we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_we0),
    .lineBuffer_val_V_0_i_d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_d0),
    .lineBuffer_val_V_0_i_address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_address1),
    .lineBuffer_val_V_0_i_ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_0_i_ce1),
    .lineBuffer_val_V_0_i_q1(lineBuffer_val_V_0_q1),
    .lineBuffer_val_V_1_i_address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_address0),
    .lineBuffer_val_V_1_i_ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_ce0),
    .lineBuffer_val_V_1_i_we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_we0),
    .lineBuffer_val_V_1_i_d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_d0),
    .lineBuffer_val_V_1_i_address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_address1),
    .lineBuffer_val_V_1_i_ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_lineBuffer_val_V_1_i_ce1),
    .lineBuffer_val_V_1_i_q1(lineBuffer_val_V_1_q1),
    .cmp37_i(cmp37_i_reg_3249),
    .cmp140_i(cmp140_i_reg_3254),
    .idxprom369_t_i(idxprom369_t_i_reg_3244),
    .red_i(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_red_i),
    .idxprom238_t_i(idxprom238_t_i_reg_3239),
    .pixBuf_val_V_2_11_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_11_1_i_out),
    .pixBuf_val_V_2_11_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_11_1_i_out_ap_vld),
    .pixBuf_val_V_2_10_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_10_1_i_out),
    .pixBuf_val_V_2_10_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_10_1_i_out_ap_vld),
    .pixBuf_val_V_2_9_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_9_1_i_out),
    .pixBuf_val_V_2_9_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_9_1_i_out_ap_vld),
    .pixBuf_val_V_2_8_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_8_1_i_out),
    .pixBuf_val_V_2_8_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_8_1_i_out_ap_vld),
    .pixBuf_val_V_2_7_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_7_1_i_out),
    .pixBuf_val_V_2_7_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_7_1_i_out_ap_vld),
    .pixBuf_val_V_2_6_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_6_1_i_out),
    .pixBuf_val_V_2_6_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_6_1_i_out_ap_vld),
    .pixBuf_val_V_2_5_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_5_1_i_out),
    .pixBuf_val_V_2_5_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_5_1_i_out_ap_vld),
    .pixBuf_val_V_2_4_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_4_1_i_out),
    .pixBuf_val_V_2_4_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_4_1_i_out_ap_vld),
    .pixBuf_val_V_2_3_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_3_1_i_out),
    .pixBuf_val_V_2_3_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_3_1_i_out_ap_vld),
    .pixBuf_val_V_2_2_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_2_1_i_out),
    .pixBuf_val_V_2_2_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_2_1_i_out_ap_vld),
    .pixBuf_val_V_2_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_1_1_i_out),
    .pixBuf_val_V_2_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_1_1_i_out_ap_vld),
    .pixBuf_val_V_2_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_0_1_i_out),
    .pixBuf_val_V_2_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_0_1_i_out_ap_vld),
    .pixBuf_val_V_1_11_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_11_1_i_out),
    .pixBuf_val_V_1_11_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_11_1_i_out_ap_vld),
    .pixBuf_val_V_1_10_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_10_1_i_out),
    .pixBuf_val_V_1_10_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_10_1_i_out_ap_vld),
    .pixBuf_val_V_1_9_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_9_1_i_out),
    .pixBuf_val_V_1_9_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_9_1_i_out_ap_vld),
    .pixBuf_val_V_1_8_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_8_1_i_out),
    .pixBuf_val_V_1_8_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_8_1_i_out_ap_vld),
    .pixBuf_val_V_1_7_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_7_1_i_out),
    .pixBuf_val_V_1_7_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_7_1_i_out_ap_vld),
    .pixBuf_val_V_1_6_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_6_1_i_out),
    .pixBuf_val_V_1_6_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_6_1_i_out_ap_vld),
    .pixBuf_val_V_1_5_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_5_1_i_out),
    .pixBuf_val_V_1_5_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_5_1_i_out_ap_vld),
    .pixBuf_val_V_1_4_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_4_1_i_out),
    .pixBuf_val_V_1_4_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_4_1_i_out_ap_vld),
    .pixBuf_val_V_1_3_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_3_1_i_out),
    .pixBuf_val_V_1_3_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_3_1_i_out_ap_vld),
    .pixBuf_val_V_1_2_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_2_1_i_out),
    .pixBuf_val_V_1_2_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_2_1_i_out_ap_vld),
    .pixBuf_val_V_1_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_1_1_i_out),
    .pixBuf_val_V_1_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_1_1_i_out_ap_vld),
    .pixBuf_val_V_1_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_0_1_i_out),
    .pixBuf_val_V_1_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_0_1_i_out_ap_vld),
    .pixBuf_val_V_0_11_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_11_1_i_out),
    .pixBuf_val_V_0_11_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_11_1_i_out_ap_vld),
    .pixBuf_val_V_0_10_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_10_1_i_out),
    .pixBuf_val_V_0_10_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_10_1_i_out_ap_vld),
    .pixBuf_val_V_0_9_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_9_1_i_out),
    .pixBuf_val_V_0_9_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_9_1_i_out_ap_vld),
    .pixBuf_val_V_0_8_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_8_1_i_out),
    .pixBuf_val_V_0_8_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_8_1_i_out_ap_vld),
    .pixBuf_val_V_0_7_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_7_1_i_out),
    .pixBuf_val_V_0_7_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_7_1_i_out_ap_vld),
    .pixBuf_val_V_0_6_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_6_1_i_out),
    .pixBuf_val_V_0_6_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_6_1_i_out_ap_vld),
    .pixBuf_val_V_0_5_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_5_1_i_out),
    .pixBuf_val_V_0_5_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_5_1_i_out_ap_vld),
    .pixBuf_val_V_0_4_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_4_1_i_out),
    .pixBuf_val_V_0_4_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_4_1_i_out_ap_vld),
    .pixBuf_val_V_0_3_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_3_1_i_out),
    .pixBuf_val_V_0_3_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_3_1_i_out_ap_vld),
    .pixBuf_val_V_0_2_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_2_1_i_out),
    .pixBuf_val_V_0_2_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_2_1_i_out_ap_vld),
    .pixBuf_val_V_0_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_1_1_i_out),
    .pixBuf_val_V_0_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_1_1_i_out_ap_vld),
    .pixBuf_val_V_0_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_0_1_i_out),
    .pixBuf_val_V_0_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_4_2_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_2_1_i_out),
    .pixWindow_val_val_V_2_4_2_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_2_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_4_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_1_1_i_out),
    .pixWindow_val_val_V_2_4_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_1_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_4_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_0_1_i_out),
    .pixWindow_val_val_V_2_4_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_3_2_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_2_i_out),
    .pixWindow_val_val_V_2_3_2_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_2_i_out_ap_vld),
    .pixWindow_val_val_V_2_3_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_1_i_out),
    .pixWindow_val_val_V_2_3_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_3_0_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_0_i_out),
    .pixWindow_val_val_V_2_3_0_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_0_i_out_ap_vld),
    .pixWindow_val_val_V_2_2_2_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_2_i_out),
    .pixWindow_val_val_V_2_2_2_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_2_i_out_ap_vld),
    .pixWindow_val_val_V_2_2_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_1_i_out),
    .pixWindow_val_val_V_2_2_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_2_0_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_0_i_out),
    .pixWindow_val_val_V_2_2_0_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_0_i_out_ap_vld),
    .pixWindow_val_val_V_2_1_2_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_2_i_out),
    .pixWindow_val_val_V_2_1_2_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_2_i_out_ap_vld),
    .pixWindow_val_val_V_2_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_1_i_out),
    .pixWindow_val_val_V_2_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_1_0_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_0_i_out),
    .pixWindow_val_val_V_2_1_0_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_0_i_out_ap_vld),
    .pixWindow_val_val_V_2_0_2_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_2_i_out),
    .pixWindow_val_val_V_2_0_2_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_2_i_out_ap_vld),
    .pixWindow_val_val_V_2_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_1_i_out),
    .pixWindow_val_val_V_2_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_0_0_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_0_i_out),
    .pixWindow_val_val_V_2_0_0_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_0_i_out_ap_vld),
    .pixWindow_val_val_V_1_4_2_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_2_1_i_out),
    .pixWindow_val_val_V_1_4_2_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_2_1_i_out_ap_vld),
    .pixWindow_val_val_V_1_4_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_1_1_i_out),
    .pixWindow_val_val_V_1_4_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_1_1_i_out_ap_vld),
    .pixWindow_val_val_V_1_4_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_0_1_i_out),
    .pixWindow_val_val_V_1_4_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_1_3_2_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_2_i_out),
    .pixWindow_val_val_V_1_3_2_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_2_i_out_ap_vld),
    .pixWindow_val_val_V_1_3_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_1_i_out),
    .pixWindow_val_val_V_1_3_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_1_i_out_ap_vld),
    .pixWindow_val_val_V_1_3_0_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_0_i_out),
    .pixWindow_val_val_V_1_3_0_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_0_i_out_ap_vld),
    .pixWindow_val_val_V_1_2_2_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_2_i_out),
    .pixWindow_val_val_V_1_2_2_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_2_i_out_ap_vld),
    .pixWindow_val_val_V_1_2_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_1_i_out),
    .pixWindow_val_val_V_1_2_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_1_i_out_ap_vld),
    .pixWindow_val_val_V_1_2_0_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_0_i_out),
    .pixWindow_val_val_V_1_2_0_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_0_i_out_ap_vld),
    .pixWindow_val_val_V_1_1_2_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_2_i_out),
    .pixWindow_val_val_V_1_1_2_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_2_i_out_ap_vld),
    .pixWindow_val_val_V_1_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_1_i_out),
    .pixWindow_val_val_V_1_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_1_i_out_ap_vld),
    .pixWindow_val_val_V_1_1_0_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_0_i_out),
    .pixWindow_val_val_V_1_1_0_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_0_i_out_ap_vld),
    .pixWindow_val_val_V_0_4_2_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_2_1_i_out),
    .pixWindow_val_val_V_0_4_2_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_2_1_i_out_ap_vld),
    .pixWindow_val_val_V_0_4_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_1_1_i_out),
    .pixWindow_val_val_V_0_4_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_1_1_i_out_ap_vld),
    .pixWindow_val_val_V_0_4_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_0_1_i_out),
    .pixWindow_val_val_V_0_4_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_0_3_2_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_2_i_out),
    .pixWindow_val_val_V_0_3_2_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_2_i_out_ap_vld),
    .pixWindow_val_val_V_0_3_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_1_i_out),
    .pixWindow_val_val_V_0_3_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_1_i_out_ap_vld),
    .pixWindow_val_val_V_0_3_0_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_0_i_out),
    .pixWindow_val_val_V_0_3_0_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_0_i_out_ap_vld),
    .pixWindow_val_val_V_0_2_2_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_2_i_out),
    .pixWindow_val_val_V_0_2_2_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_2_i_out_ap_vld),
    .pixWindow_val_val_V_0_2_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_1_i_out),
    .pixWindow_val_val_V_0_2_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_1_i_out_ap_vld),
    .pixWindow_val_val_V_0_2_0_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_0_i_out),
    .pixWindow_val_val_V_0_2_0_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_0_i_out_ap_vld),
    .pixWindow_val_val_V_0_1_2_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_2_i_out),
    .pixWindow_val_val_V_0_1_2_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_2_i_out_ap_vld),
    .pixWindow_val_val_V_0_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_1_i_out),
    .pixWindow_val_val_V_0_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_1_i_out_ap_vld),
    .pixWindow_val_val_V_0_1_0_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_0_i_out),
    .pixWindow_val_val_V_0_1_0_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_0_i_out_ap_vld),
    .pixWindow_val_val_V_0_0_2_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_2_i_out),
    .pixWindow_val_val_V_0_0_2_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_2_i_out_ap_vld),
    .pixWindow_val_val_V_0_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_1_i_out),
    .pixWindow_val_val_V_0_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_0_0_0_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_0_i_out),
    .pixWindow_val_val_V_0_0_0_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_0_i_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln582_fu_986_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln582_fu_986_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_start_reg <= 1'b1;
        end else if ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_ready == 1'b1)) begin
            grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_80 <= 12'd0;
    end else if (((icmp_ln582_fu_986_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_80 <= y_4_fu_991_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln582_fu_986_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        cmp140_i_reg_3254 <= cmp140_i_fu_1365_p2;
        cmp37_i_reg_3249 <= cmp37_i_fu_1359_p2;
        icmp_ln724_1_reg_3264 <= icmp_ln724_1_fu_1378_p2;
        icmp_ln724_reg_3259 <= icmp_ln724_fu_1372_p2;
        idxprom238_t_i_reg_3239[1] <= idxprom238_t_i_fu_1341_p3[1];
        idxprom369_t_i_reg_3244[1] <= idxprom369_t_i_fu_1350_p3[1];
        out_y_i_reg_3229 <= out_y_i_fu_1313_p2;
        red_i_reg_3234 <= red_i_fu_1335_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pixBuf_val_V_0_0_0_i_fu_252 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_0_1_i_out;
        pixBuf_val_V_0_10_0_i_fu_292 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_10_1_i_out;
        pixBuf_val_V_0_11_0_i_fu_296 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_11_1_i_out;
        pixBuf_val_V_0_1_0_i_fu_256 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_1_1_i_out;
        pixBuf_val_V_0_2_0_i_fu_260 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_2_1_i_out;
        pixBuf_val_V_0_3_0_i_fu_264 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_3_1_i_out;
        pixBuf_val_V_0_4_0_i_fu_268 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_4_1_i_out;
        pixBuf_val_V_0_5_0_i_fu_272 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_5_1_i_out;
        pixBuf_val_V_0_6_0_i_fu_276 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_6_1_i_out;
        pixBuf_val_V_0_7_0_i_fu_280 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_7_1_i_out;
        pixBuf_val_V_0_8_0_i_fu_284 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_8_1_i_out;
        pixBuf_val_V_0_9_0_i_fu_288 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_0_9_1_i_out;
        pixBuf_val_V_1_0_03224_i_fu_300 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_0_1_i_out;
        pixBuf_val_V_1_10_03234_i_fu_340 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_10_1_i_out;
        pixBuf_val_V_1_11_03235_i_fu_344 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_11_1_i_out;
        pixBuf_val_V_1_1_03225_i_fu_304 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_1_1_i_out;
        pixBuf_val_V_1_2_03226_i_fu_308 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_2_1_i_out;
        pixBuf_val_V_1_3_03227_i_fu_312 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_3_1_i_out;
        pixBuf_val_V_1_4_03228_i_fu_316 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_4_1_i_out;
        pixBuf_val_V_1_5_03229_i_fu_320 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_5_1_i_out;
        pixBuf_val_V_1_6_03230_i_fu_324 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_6_1_i_out;
        pixBuf_val_V_1_7_03231_i_fu_328 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_7_1_i_out;
        pixBuf_val_V_1_8_03232_i_fu_332 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_8_1_i_out;
        pixBuf_val_V_1_9_03233_i_fu_336 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_1_9_1_i_out;
        pixBuf_val_V_2_0_03236_i_fu_348 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_0_1_i_out;
        pixBuf_val_V_2_10_03246_i_fu_388 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_10_1_i_out;
        pixBuf_val_V_2_11_03247_i_fu_392 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_11_1_i_out;
        pixBuf_val_V_2_1_03237_i_fu_352 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_1_1_i_out;
        pixBuf_val_V_2_2_03238_i_fu_356 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_2_1_i_out;
        pixBuf_val_V_2_3_03239_i_fu_360 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_3_1_i_out;
        pixBuf_val_V_2_4_03240_i_fu_364 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_4_1_i_out;
        pixBuf_val_V_2_5_03241_i_fu_368 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_5_1_i_out;
        pixBuf_val_V_2_6_03242_i_fu_372 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_6_1_i_out;
        pixBuf_val_V_2_7_03243_i_fu_376 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_7_1_i_out;
        pixBuf_val_V_2_8_03244_i_fu_380 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_8_1_i_out;
        pixBuf_val_V_2_9_03245_i_fu_384 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixBuf_val_V_2_9_1_i_out;
        pixWindow_val_val_V_0_4_0_0_i_fu_84 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_0_i_out;
        pixWindow_val_val_V_0_4_1_0_i_fu_88 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_1_i_out;
        pixWindow_val_val_V_0_4_2_0_i_fu_92 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_0_2_i_out;
        pixWindow_val_val_V_0_5_0_0_i_fu_96 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_0_i_out;
        pixWindow_val_val_V_0_5_1_0_i_fu_100 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_1_i_out;
        pixWindow_val_val_V_0_5_2_0_i_fu_104 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_1_2_i_out;
        pixWindow_val_val_V_0_6_0_0_i_fu_108 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_0_i_out;
        pixWindow_val_val_V_0_6_1_0_i_fu_112 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_1_i_out;
        pixWindow_val_val_V_0_6_2_0_i_fu_116 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_2_2_i_out;
        pixWindow_val_val_V_0_7_0_0_i_fu_120 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_0_i_out;
        pixWindow_val_val_V_0_7_1_0_i_fu_124 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_1_i_out;
        pixWindow_val_val_V_0_7_2_0_i_fu_128 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_3_2_i_out;
        pixWindow_val_val_V_0_8_0_0_i_fu_132 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_0_1_i_out;
        pixWindow_val_val_V_0_8_1_0_i_fu_136 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_1_1_i_out;
        pixWindow_val_val_V_0_8_2_0_i_fu_140 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_0_4_2_1_i_out;
        pixWindow_val_val_V_1_5_0_0_i_fu_144 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_0_i_out;
        pixWindow_val_val_V_1_5_1_0_i_fu_148 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_1_i_out;
        pixWindow_val_val_V_1_5_2_0_i_fu_152 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_1_2_i_out;
        pixWindow_val_val_V_1_6_0_0_i_fu_156 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_0_i_out;
        pixWindow_val_val_V_1_6_1_0_i_fu_160 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_1_i_out;
        pixWindow_val_val_V_1_6_2_0_i_fu_164 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_2_2_i_out;
        pixWindow_val_val_V_1_7_0_0_i_fu_168 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_0_i_out;
        pixWindow_val_val_V_1_7_1_0_i_fu_172 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_1_i_out;
        pixWindow_val_val_V_1_7_2_0_i_fu_176 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_3_2_i_out;
        pixWindow_val_val_V_1_8_0_0_i_fu_180 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_0_1_i_out;
        pixWindow_val_val_V_1_8_1_0_i_fu_184 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_1_1_i_out;
        pixWindow_val_val_V_1_8_2_0_i_fu_188 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_1_4_2_1_i_out;
        pixWindow_val_val_V_2_4_0_0_i_fu_192 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_0_i_out;
        pixWindow_val_val_V_2_4_1_0_i_fu_196 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_1_i_out;
        pixWindow_val_val_V_2_4_2_0_i_fu_200 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_0_2_i_out;
        pixWindow_val_val_V_2_5_0_0_i_fu_204 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_0_i_out;
        pixWindow_val_val_V_2_5_1_0_i_fu_208 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_1_i_out;
        pixWindow_val_val_V_2_5_2_0_i_fu_212 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_1_2_i_out;
        pixWindow_val_val_V_2_6_0_0_i_fu_216 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_0_i_out;
        pixWindow_val_val_V_2_6_1_0_i_fu_220 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_1_i_out;
        pixWindow_val_val_V_2_6_2_0_i_fu_224 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_2_2_i_out;
        pixWindow_val_val_V_2_7_0_0_i_fu_228 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_0_i_out;
        pixWindow_val_val_V_2_7_1_0_i_fu_232 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_1_i_out;
        pixWindow_val_val_V_2_7_2_0_i_fu_236 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_3_2_i_out;
        pixWindow_val_val_V_2_8_0_0_i_fu_240 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_0_1_i_out;
        pixWindow_val_val_V_2_8_1_0_i_fu_244 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_1_1_i_out;
        pixWindow_val_val_V_2_8_2_0_i_fu_248 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_pixWindow_val_val_V_2_4_2_1_i_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln574_1_i_reg_2971 <= {{bayerPhase_c9_dout[15:1]}};
        zext_ln575_reg_2977[0] <= zext_ln575_fu_938_p1[0];
        zext_ln724_reg_2987[0] <= zext_ln724_fu_970_p1[0];
    end
end

always @ (*) begin
    if (((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln582_fu_986_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c9_blk_n = bayerPhase_c9_empty_n;
    end else begin
        bayerPhase_c9_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c9_read = 1'b1;
    end else begin
        bayerPhase_c9_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c_blk_n = bayerPhase_c_full_n;
    end else begin
        bayerPhase_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c_write = 1'b1;
    end else begin
        bayerPhase_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgG_read = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_imgG_read;
    end else begin
        imgG_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgRB_write = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_imgRB_write;
    end else begin
        imgRB_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln582_fu_986_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln582_fu_986_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln582_fu_942_p2 = (width + 12'd3);

assign and219_cast_i_fu_1326_p1 = out_y_cast_i_fu_1320_p2;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign bayerPhase_c_din = bayerPhase_c9_dout;

assign cmp140_i_fu_1365_p2 = ((y_fu_80 != 12'd0) ? 1'b1 : 1'b0);

assign cmp37_i_fu_1359_p2 = ((y_fu_80 < height) ? 1'b1 : 1'b0);

assign empty_182_fu_1309_p1 = y_fu_80[0:0];

assign grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_add_ln582_1_i = (trunc_ln_i_fu_948_p4 + 10'd1);

assign grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_start = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_ap_start_reg;

assign grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_red_i = red_i_reg_3234;

assign icmp_ln582_fu_986_p2 = ((y_fu_80 == loopHeight_fu_918_p2) ? 1'b1 : 1'b0);

assign icmp_ln724_1_fu_1378_p2 = ((xor_i_fu_1330_p2 == zext_ln724_reg_2987) ? 1'b1 : 1'b0);

assign icmp_ln724_fu_1372_p2 = ((xor_i_fu_1330_p2 == zext_ln575_reg_2977) ? 1'b1 : 1'b0);

assign idxprom238_t_i_fu_1341_p3 = ((red_i_fu_1335_p2[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign idxprom369_t_i_fu_1350_p3 = ((red_i_fu_1335_p2[0:0] == 1'b1) ? 2'd2 : 2'd0);

assign imgRB_din = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_742_imgRB_din;

assign loopHeight_fu_918_p2 = (height + 12'd1);

assign out_y_cast_i_fu_1320_p2 = (empty_182_fu_1309_p1 ^ 1'd1);

assign out_y_i_fu_1313_p2 = ($signed(zext_ln582_fu_982_p1) + $signed(13'd8191));

assign red_i_fu_1335_p2 = ((and219_cast_i_fu_1326_p1 == trunc_ln574_1_i_reg_2971) ? 1'b1 : 1'b0);

assign start_out = real_start;

assign trunc_ln_i_fu_948_p4 = {{add_ln582_fu_942_p2[11:2]}};

assign x_phase_fu_924_p1 = bayerPhase_c9_dout[0:0];

assign xor_i_fu_1330_p2 = (trunc_ln574_1_i_reg_2971 ^ and219_cast_i_fu_1326_p1);

assign xor_ln724_fu_964_p2 = (x_phase_fu_924_p1 ^ 1'd1);

assign y_4_fu_991_p2 = (y_fu_80 + 12'd1);

assign zext_ln575_fu_938_p1 = x_phase_fu_924_p1;

assign zext_ln582_fu_982_p1 = y_fu_80;

assign zext_ln724_fu_970_p1 = xor_ln724_fu_964_p2;

always @ (posedge ap_clk) begin
    zext_ln575_reg_2977[14:1] <= 14'b00000000000000;
    zext_ln724_reg_2987[14:1] <= 14'b00000000000000;
    idxprom238_t_i_reg_3239[0] <= 1'b0;
    idxprom369_t_i_reg_3244[0] <= 1'b0;
end

endmodule //design_0_v_demosaic_0_0_DebayerRatBorBatR
