// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_0_v_demosaic_0_0_DebayerG (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        imgBayer_dout,
        imgBayer_empty_n,
        imgBayer_read,
        imgG_din,
        imgG_full_n,
        imgG_write,
        height,
        width,
        p_read,
        bayerPhase_c9_din,
        bayerPhase_c9_full_n,
        bayerPhase_c9_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] imgBayer_dout;
input   imgBayer_empty_n;
output   imgBayer_read;
output  [95:0] imgG_din;
input   imgG_full_n;
output   imgG_write;
input  [15:0] height;
input  [15:0] width;
input  [15:0] p_read;
output  [15:0] bayerPhase_c9_din;
input   bayerPhase_c9_full_n;
output   bayerPhase_c9_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg imgBayer_read;
reg imgG_write;
reg bayerPhase_c9_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    bayerPhase_c9_blk_n;
wire   [16:0] zext_ln225_fu_652_p1;
wire   [16:0] loopHeight_fu_656_p2;
reg   [14:0] trunc_ln244_1_reg_2013;
wire   [14:0] zext_ln245_fu_680_p1;
reg   [14:0] zext_ln245_reg_2019;
wire   [14:0] zext_ln390_fu_712_p1;
reg   [14:0] zext_ln390_reg_2029;
wire   [16:0] out_y_fu_939_p2;
reg   [16:0] out_y_reg_2187;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln266_fu_724_p2;
wire   [0:0] cmp610_fu_955_p2;
reg   [0:0] cmp610_reg_2192;
wire   [0:0] cmp47_fu_961_p2;
reg   [0:0] cmp47_reg_2197;
wire   [0:0] cmp101_fu_967_p2;
reg   [0:0] cmp101_reg_2202;
wire   [0:0] icmp_ln390_fu_974_p2;
reg   [0:0] icmp_ln390_reg_2207;
wire   [0:0] icmp_ln390_1_fu_980_p2;
reg   [0:0] icmp_ln390_1_reg_2212;
wire   [31:0] linebuf_yuv_val_V_0_q1;
wire   [31:0] linebuf_yuv_val_V_1_q1;
wire   [31:0] linebuf_yuv_val_V_2_q1;
wire   [31:0] linebuf_yuv_val_V_3_q1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_start;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_done;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_idle;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_ready;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_imgBayer_read;
wire   [95:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_imgG_din;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_imgG_write;
wire   [14:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_add_ln266_1;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_address0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_ce0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_we0;
wire   [31:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_d0;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_address1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_ce1;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_address0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_ce0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_we0;
wire   [31:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_d0;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_address1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_ce1;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_address0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_ce0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_we0;
wire   [31:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_d0;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_address1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_ce1;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_address0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_ce0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_we0;
wire   [31:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_d0;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_address1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_ce1;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_3_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_3_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_2_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_2_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_1_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_1_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_0_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_0_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_3_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_3_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_2_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_2_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_1_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_1_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_0_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_0_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_3_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_3_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_2_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_2_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_1_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_1_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_0_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_0_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_3_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_3_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_2_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_2_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_1_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_1_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_0_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_0_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_3_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_3_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_2_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_2_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_1_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_1_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_0_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_0_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_5_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_5_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_4_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_4_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_3_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_3_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_2_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_2_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_0_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_0_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_5_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_5_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_4_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_4_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_3_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_3_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_2_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_2_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_0_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_0_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_5_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_5_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_4_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_4_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_3_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_3_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_2_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_2_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_0_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_0_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_5_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_5_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_4_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_4_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_3_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_3_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_2_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_2_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_0_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_0_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_5_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_5_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_4_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_4_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_3_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_3_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_2_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_2_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_1_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_1_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_0_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_0_out_ap_vld;
reg    grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [16:0] y_fu_82;
wire   [16:0] y_8_fu_729_p2;
reg    ap_block_state1;
reg   [7:0] bayerWindow_val_V_0_4_0_fu_86;
wire    ap_CS_fsm_state4;
reg   [7:0] bayerWindow_val_V_0_5_0_fu_90;
reg   [7:0] bayerWindow_val_V_0_6_0_fu_94;
reg   [7:0] bayerWindow_val_V_0_7_0_fu_98;
reg   [7:0] bayerWindow_val_V_0_8_0_fu_102;
reg   [7:0] bayerWindow_val_V_0_9_0_fu_106;
reg   [7:0] bayerWindow_val_V_1_4_0_fu_110;
reg   [7:0] bayerWindow_val_V_1_5_0_fu_114;
reg   [7:0] bayerWindow_val_V_1_6_0_fu_118;
reg   [7:0] bayerWindow_val_V_1_7_0_fu_122;
reg   [7:0] bayerWindow_val_V_1_8_0_fu_126;
reg   [7:0] bayerWindow_val_V_1_9_0_fu_130;
reg   [7:0] bayerWindow_val_V_2_4_0_fu_134;
reg   [7:0] bayerWindow_val_V_2_5_0_fu_138;
reg   [7:0] bayerWindow_val_V_2_6_0_fu_142;
reg   [7:0] bayerWindow_val_V_2_7_0_fu_146;
reg   [7:0] bayerWindow_val_V_2_8_0_fu_150;
reg   [7:0] bayerWindow_val_V_2_9_0_fu_154;
reg   [7:0] bayerWindow_val_V_3_4_0_fu_158;
reg   [7:0] bayerWindow_val_V_3_5_0_fu_162;
reg   [7:0] bayerWindow_val_V_3_6_0_fu_166;
reg   [7:0] bayerWindow_val_V_3_7_0_fu_170;
reg   [7:0] bayerWindow_val_V_3_8_0_fu_174;
reg   [7:0] bayerWindow_val_V_3_9_0_fu_178;
reg   [7:0] bayerWindow_val_V_4_4_0_fu_182;
reg   [7:0] bayerWindow_val_V_4_5_0_fu_186;
reg   [7:0] bayerWindow_val_V_4_6_0_fu_190;
reg   [7:0] bayerWindow_val_V_4_7_0_fu_194;
reg   [7:0] bayerWindow_val_V_4_8_0_fu_198;
reg   [7:0] bayerWindow_val_V_4_9_0_fu_202;
reg   [7:0] pixBuf_val_V_0_0_0_fu_206;
reg   [7:0] pixBuf_val_V_0_1_0_fu_210;
reg   [7:0] pixBuf_val_V_0_2_0_fu_214;
reg   [7:0] pixBuf_val_V_0_3_0_fu_218;
reg   [7:0] pixBuf_val_V_1_0_01817_fu_222;
reg   [7:0] pixBuf_val_V_1_1_01818_fu_226;
reg   [7:0] pixBuf_val_V_1_2_01819_fu_230;
reg   [7:0] pixBuf_val_V_1_3_01820_fu_234;
reg   [7:0] pixBuf_val_V_2_0_01821_fu_238;
reg   [7:0] pixBuf_val_V_2_1_01822_fu_242;
reg   [7:0] pixBuf_val_V_2_2_01823_fu_246;
reg   [7:0] pixBuf_val_V_2_3_01824_fu_250;
reg   [7:0] pixBuf_val_V_3_0_01825_fu_254;
reg   [7:0] pixBuf_val_V_3_1_01826_fu_258;
reg   [7:0] pixBuf_val_V_3_2_01827_fu_262;
reg   [7:0] pixBuf_val_V_3_3_01828_fu_266;
reg   [7:0] pixBuf_val_V_4_0_01829_fu_270;
reg   [7:0] pixBuf_val_V_4_1_01830_fu_274;
reg   [7:0] pixBuf_val_V_4_2_01831_fu_278;
reg   [7:0] pixBuf_val_V_4_3_01832_fu_282;
wire   [0:0] x_phase_fu_666_p1;
wire   [16:0] zext_ln234_fu_662_p1;
wire   [16:0] add_ln266_fu_684_p2;
wire   [14:0] trunc_ln_fu_690_p4;
wire   [0:0] xor_ln390_fu_706_p2;
wire   [0:0] empty_196_fu_935_p1;
wire   [14:0] and161_cast_fu_946_p1;
wire   [14:0] xor_fu_950_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_start_reg = 1'b0;
end

design_0_v_demosaic_0_0_DebayerG_linebuf_yuv_val_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 961 ),
    .AddressWidth( 10 ))
linebuf_yuv_val_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_address0),
    .ce0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_ce0),
    .we0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_we0),
    .d0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_d0),
    .address1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_address1),
    .ce1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_ce1),
    .q1(linebuf_yuv_val_V_0_q1)
);

design_0_v_demosaic_0_0_DebayerG_linebuf_yuv_val_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 961 ),
    .AddressWidth( 10 ))
linebuf_yuv_val_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_address0),
    .ce0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_ce0),
    .we0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_we0),
    .d0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_d0),
    .address1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_address1),
    .ce1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_ce1),
    .q1(linebuf_yuv_val_V_1_q1)
);

design_0_v_demosaic_0_0_DebayerG_linebuf_yuv_val_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 961 ),
    .AddressWidth( 10 ))
linebuf_yuv_val_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_address0),
    .ce0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_ce0),
    .we0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_we0),
    .d0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_d0),
    .address1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_address1),
    .ce1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_ce1),
    .q1(linebuf_yuv_val_V_2_q1)
);

design_0_v_demosaic_0_0_DebayerG_linebuf_yuv_val_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 961 ),
    .AddressWidth( 10 ))
linebuf_yuv_val_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_address0),
    .ce0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_ce0),
    .we0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_we0),
    .d0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_d0),
    .address1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_address1),
    .ce1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_ce1),
    .q1(linebuf_yuv_val_V_3_q1)
);

design_0_v_demosaic_0_0_DebayerG_Pipeline_VITIS_LOOP_269_4 grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_start),
    .ap_done(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_done),
    .ap_idle(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_idle),
    .ap_ready(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_ready),
    .imgBayer_dout(imgBayer_dout),
    .imgBayer_empty_n(imgBayer_empty_n),
    .imgBayer_read(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_imgBayer_read),
    .imgG_din(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_imgG_din),
    .imgG_full_n(imgG_full_n),
    .imgG_write(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_imgG_write),
    .pixBuf_val_V_4_3_01832(pixBuf_val_V_4_3_01832_fu_282),
    .pixBuf_val_V_4_2_01831(pixBuf_val_V_4_2_01831_fu_278),
    .pixBuf_val_V_4_1_01830(pixBuf_val_V_4_1_01830_fu_274),
    .pixBuf_val_V_4_0_01829(pixBuf_val_V_4_0_01829_fu_270),
    .pixBuf_val_V_3_3_01828(pixBuf_val_V_3_3_01828_fu_266),
    .pixBuf_val_V_3_2_01827(pixBuf_val_V_3_2_01827_fu_262),
    .pixBuf_val_V_3_1_01826(pixBuf_val_V_3_1_01826_fu_258),
    .pixBuf_val_V_3_0_01825(pixBuf_val_V_3_0_01825_fu_254),
    .pixBuf_val_V_2_3_01824(pixBuf_val_V_2_3_01824_fu_250),
    .pixBuf_val_V_2_2_01823(pixBuf_val_V_2_2_01823_fu_246),
    .pixBuf_val_V_2_1_01822(pixBuf_val_V_2_1_01822_fu_242),
    .pixBuf_val_V_2_0_01821(pixBuf_val_V_2_0_01821_fu_238),
    .pixBuf_val_V_1_3_01820(pixBuf_val_V_1_3_01820_fu_234),
    .pixBuf_val_V_1_2_01819(pixBuf_val_V_1_2_01819_fu_230),
    .pixBuf_val_V_1_1_01818(pixBuf_val_V_1_1_01818_fu_226),
    .pixBuf_val_V_1_0_01817(pixBuf_val_V_1_0_01817_fu_222),
    .pixBuf_val_V_0_3_0(pixBuf_val_V_0_3_0_fu_218),
    .pixBuf_val_V_0_2_0(pixBuf_val_V_0_2_0_fu_214),
    .pixBuf_val_V_0_1_0(pixBuf_val_V_0_1_0_fu_210),
    .pixBuf_val_V_0_0_0(pixBuf_val_V_0_0_0_fu_206),
    .bayerWindow_val_V_4_9_0(bayerWindow_val_V_4_9_0_fu_202),
    .bayerWindow_val_V_4_8_0(bayerWindow_val_V_4_8_0_fu_198),
    .bayerWindow_val_V_4_7_0(bayerWindow_val_V_4_7_0_fu_194),
    .bayerWindow_val_V_4_6_0(bayerWindow_val_V_4_6_0_fu_190),
    .bayerWindow_val_V_4_5_0(bayerWindow_val_V_4_5_0_fu_186),
    .bayerWindow_val_V_4_4_0(bayerWindow_val_V_4_4_0_fu_182),
    .bayerWindow_val_V_3_9_0(bayerWindow_val_V_3_9_0_fu_178),
    .bayerWindow_val_V_3_8_0(bayerWindow_val_V_3_8_0_fu_174),
    .bayerWindow_val_V_3_7_0(bayerWindow_val_V_3_7_0_fu_170),
    .bayerWindow_val_V_3_6_0(bayerWindow_val_V_3_6_0_fu_166),
    .bayerWindow_val_V_3_5_0(bayerWindow_val_V_3_5_0_fu_162),
    .bayerWindow_val_V_3_4_0(bayerWindow_val_V_3_4_0_fu_158),
    .bayerWindow_val_V_2_9_0(bayerWindow_val_V_2_9_0_fu_154),
    .bayerWindow_val_V_2_8_0(bayerWindow_val_V_2_8_0_fu_150),
    .bayerWindow_val_V_2_7_0(bayerWindow_val_V_2_7_0_fu_146),
    .bayerWindow_val_V_2_6_0(bayerWindow_val_V_2_6_0_fu_142),
    .bayerWindow_val_V_2_5_0(bayerWindow_val_V_2_5_0_fu_138),
    .bayerWindow_val_V_2_4_0(bayerWindow_val_V_2_4_0_fu_134),
    .bayerWindow_val_V_1_9_0(bayerWindow_val_V_1_9_0_fu_130),
    .bayerWindow_val_V_1_8_0(bayerWindow_val_V_1_8_0_fu_126),
    .bayerWindow_val_V_1_7_0(bayerWindow_val_V_1_7_0_fu_122),
    .bayerWindow_val_V_1_6_0(bayerWindow_val_V_1_6_0_fu_118),
    .bayerWindow_val_V_1_5_0(bayerWindow_val_V_1_5_0_fu_114),
    .bayerWindow_val_V_1_4_0(bayerWindow_val_V_1_4_0_fu_110),
    .bayerWindow_val_V_0_9_0(bayerWindow_val_V_0_9_0_fu_106),
    .bayerWindow_val_V_0_8_0(bayerWindow_val_V_0_8_0_fu_102),
    .bayerWindow_val_V_0_7_0(bayerWindow_val_V_0_7_0_fu_98),
    .bayerWindow_val_V_0_6_0(bayerWindow_val_V_0_6_0_fu_94),
    .bayerWindow_val_V_0_5_0(bayerWindow_val_V_0_5_0_fu_90),
    .bayerWindow_val_V_0_4_0(bayerWindow_val_V_0_4_0_fu_86),
    .add_ln266_1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_add_ln266_1),
    .cmp610(cmp610_reg_2192),
    .icmp_ln390(icmp_ln390_reg_2207),
    .icmp_ln390_1(icmp_ln390_1_reg_2212),
    .out_y(out_y_reg_2187),
    .zext_ln234(width),
    .linebuf_yuv_val_V_0_address0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_address0),
    .linebuf_yuv_val_V_0_ce0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_ce0),
    .linebuf_yuv_val_V_0_we0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_we0),
    .linebuf_yuv_val_V_0_d0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_d0),
    .linebuf_yuv_val_V_0_address1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_address1),
    .linebuf_yuv_val_V_0_ce1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_0_ce1),
    .linebuf_yuv_val_V_0_q1(linebuf_yuv_val_V_0_q1),
    .linebuf_yuv_val_V_1_address0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_address0),
    .linebuf_yuv_val_V_1_ce0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_ce0),
    .linebuf_yuv_val_V_1_we0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_we0),
    .linebuf_yuv_val_V_1_d0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_d0),
    .linebuf_yuv_val_V_1_address1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_address1),
    .linebuf_yuv_val_V_1_ce1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_1_ce1),
    .linebuf_yuv_val_V_1_q1(linebuf_yuv_val_V_1_q1),
    .linebuf_yuv_val_V_2_address0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_address0),
    .linebuf_yuv_val_V_2_ce0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_ce0),
    .linebuf_yuv_val_V_2_we0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_we0),
    .linebuf_yuv_val_V_2_d0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_d0),
    .linebuf_yuv_val_V_2_address1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_address1),
    .linebuf_yuv_val_V_2_ce1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_2_ce1),
    .linebuf_yuv_val_V_2_q1(linebuf_yuv_val_V_2_q1),
    .linebuf_yuv_val_V_3_address0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_address0),
    .linebuf_yuv_val_V_3_ce0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_ce0),
    .linebuf_yuv_val_V_3_we0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_we0),
    .linebuf_yuv_val_V_3_d0(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_d0),
    .linebuf_yuv_val_V_3_address1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_address1),
    .linebuf_yuv_val_V_3_ce1(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_linebuf_yuv_val_V_3_ce1),
    .linebuf_yuv_val_V_3_q1(linebuf_yuv_val_V_3_q1),
    .cmp47(cmp47_reg_2197),
    .cmp101(cmp101_reg_2202),
    .pixBuf_val_V_4_3_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_3_1_out),
    .pixBuf_val_V_4_3_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_3_1_out_ap_vld),
    .pixBuf_val_V_4_2_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_2_1_out),
    .pixBuf_val_V_4_2_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_2_1_out_ap_vld),
    .pixBuf_val_V_4_1_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_1_1_out),
    .pixBuf_val_V_4_1_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_1_1_out_ap_vld),
    .pixBuf_val_V_4_0_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_0_1_out),
    .pixBuf_val_V_4_0_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_0_1_out_ap_vld),
    .pixBuf_val_V_3_3_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_3_1_out),
    .pixBuf_val_V_3_3_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_3_1_out_ap_vld),
    .pixBuf_val_V_3_2_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_2_1_out),
    .pixBuf_val_V_3_2_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_2_1_out_ap_vld),
    .pixBuf_val_V_3_1_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_1_1_out),
    .pixBuf_val_V_3_1_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_1_1_out_ap_vld),
    .pixBuf_val_V_3_0_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_0_1_out),
    .pixBuf_val_V_3_0_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_0_1_out_ap_vld),
    .pixBuf_val_V_2_3_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_3_1_out),
    .pixBuf_val_V_2_3_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_3_1_out_ap_vld),
    .pixBuf_val_V_2_2_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_2_1_out),
    .pixBuf_val_V_2_2_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_2_1_out_ap_vld),
    .pixBuf_val_V_2_1_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_1_1_out),
    .pixBuf_val_V_2_1_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_1_1_out_ap_vld),
    .pixBuf_val_V_2_0_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_0_1_out),
    .pixBuf_val_V_2_0_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_0_1_out_ap_vld),
    .pixBuf_val_V_1_3_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_3_1_out),
    .pixBuf_val_V_1_3_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_3_1_out_ap_vld),
    .pixBuf_val_V_1_2_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_2_1_out),
    .pixBuf_val_V_1_2_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_2_1_out_ap_vld),
    .pixBuf_val_V_1_1_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_1_1_out),
    .pixBuf_val_V_1_1_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_1_1_out_ap_vld),
    .pixBuf_val_V_1_0_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_0_1_out),
    .pixBuf_val_V_1_0_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_0_1_out_ap_vld),
    .pixBuf_val_V_0_3_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_3_1_out),
    .pixBuf_val_V_0_3_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_3_1_out_ap_vld),
    .pixBuf_val_V_0_2_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_2_1_out),
    .pixBuf_val_V_0_2_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_2_1_out_ap_vld),
    .pixBuf_val_V_0_1_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_1_1_out),
    .pixBuf_val_V_0_1_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_1_1_out_ap_vld),
    .pixBuf_val_V_0_0_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_0_1_out),
    .pixBuf_val_V_0_0_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_0_1_out_ap_vld),
    .bayerWindow_val_V_4_5_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_5_1_out),
    .bayerWindow_val_V_4_5_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_5_1_out_ap_vld),
    .bayerWindow_val_V_4_4_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_4_out),
    .bayerWindow_val_V_4_4_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_4_out_ap_vld),
    .bayerWindow_val_V_4_3_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_3_out),
    .bayerWindow_val_V_4_3_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_3_out_ap_vld),
    .bayerWindow_val_V_4_2_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_2_out),
    .bayerWindow_val_V_4_2_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_2_out_ap_vld),
    .bayerWindow_val_V_4_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_1_out),
    .bayerWindow_val_V_4_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_1_out_ap_vld),
    .bayerWindow_val_V_4_0_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_0_out),
    .bayerWindow_val_V_4_0_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_0_out_ap_vld),
    .bayerWindow_val_V_3_5_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_5_1_out),
    .bayerWindow_val_V_3_5_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_5_1_out_ap_vld),
    .bayerWindow_val_V_3_4_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_4_out),
    .bayerWindow_val_V_3_4_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_4_out_ap_vld),
    .bayerWindow_val_V_3_3_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_3_out),
    .bayerWindow_val_V_3_3_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_3_out_ap_vld),
    .bayerWindow_val_V_3_2_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_2_out),
    .bayerWindow_val_V_3_2_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_2_out_ap_vld),
    .bayerWindow_val_V_3_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_1_out),
    .bayerWindow_val_V_3_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_1_out_ap_vld),
    .bayerWindow_val_V_3_0_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_0_out),
    .bayerWindow_val_V_3_0_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_0_out_ap_vld),
    .bayerWindow_val_V_2_5_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_5_1_out),
    .bayerWindow_val_V_2_5_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_5_1_out_ap_vld),
    .bayerWindow_val_V_2_4_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_4_out),
    .bayerWindow_val_V_2_4_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_4_out_ap_vld),
    .bayerWindow_val_V_2_3_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_3_out),
    .bayerWindow_val_V_2_3_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_3_out_ap_vld),
    .bayerWindow_val_V_2_2_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_2_out),
    .bayerWindow_val_V_2_2_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_2_out_ap_vld),
    .bayerWindow_val_V_2_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_1_out),
    .bayerWindow_val_V_2_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_1_out_ap_vld),
    .bayerWindow_val_V_2_0_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_0_out),
    .bayerWindow_val_V_2_0_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_0_out_ap_vld),
    .bayerWindow_val_V_1_5_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_5_1_out),
    .bayerWindow_val_V_1_5_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_5_1_out_ap_vld),
    .bayerWindow_val_V_1_4_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_4_out),
    .bayerWindow_val_V_1_4_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_4_out_ap_vld),
    .bayerWindow_val_V_1_3_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_3_out),
    .bayerWindow_val_V_1_3_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_3_out_ap_vld),
    .bayerWindow_val_V_1_2_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_2_out),
    .bayerWindow_val_V_1_2_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_2_out_ap_vld),
    .bayerWindow_val_V_1_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_1_out),
    .bayerWindow_val_V_1_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_1_out_ap_vld),
    .bayerWindow_val_V_1_0_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_0_out),
    .bayerWindow_val_V_1_0_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_0_out_ap_vld),
    .bayerWindow_val_V_0_5_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_5_1_out),
    .bayerWindow_val_V_0_5_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_5_1_out_ap_vld),
    .bayerWindow_val_V_0_4_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_4_out),
    .bayerWindow_val_V_0_4_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_4_out_ap_vld),
    .bayerWindow_val_V_0_3_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_3_out),
    .bayerWindow_val_V_0_3_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_3_out_ap_vld),
    .bayerWindow_val_V_0_2_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_2_out),
    .bayerWindow_val_V_0_2_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_2_out_ap_vld),
    .bayerWindow_val_V_0_1_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_1_out),
    .bayerWindow_val_V_0_1_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_1_out_ap_vld),
    .bayerWindow_val_V_0_0_out(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_0_out),
    .bayerWindow_val_V_0_0_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_0_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln266_fu_724_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln266_fu_724_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_start_reg <= 1'b1;
        end else if ((grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_ready == 1'b1)) begin
            grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((bayerPhase_c9_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_82 <= 17'd0;
    end else if (((icmp_ln266_fu_724_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_82 <= y_8_fu_729_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bayerWindow_val_V_0_4_0_fu_86 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_0_out;
        bayerWindow_val_V_0_5_0_fu_90 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_1_out;
        bayerWindow_val_V_0_6_0_fu_94 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_2_out;
        bayerWindow_val_V_0_7_0_fu_98 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_3_out;
        bayerWindow_val_V_0_8_0_fu_102 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_4_out;
        bayerWindow_val_V_0_9_0_fu_106 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_0_5_1_out;
        bayerWindow_val_V_1_4_0_fu_110 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_0_out;
        bayerWindow_val_V_1_5_0_fu_114 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_1_out;
        bayerWindow_val_V_1_6_0_fu_118 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_2_out;
        bayerWindow_val_V_1_7_0_fu_122 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_3_out;
        bayerWindow_val_V_1_8_0_fu_126 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_4_out;
        bayerWindow_val_V_1_9_0_fu_130 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_1_5_1_out;
        bayerWindow_val_V_2_4_0_fu_134 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_0_out;
        bayerWindow_val_V_2_5_0_fu_138 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_1_out;
        bayerWindow_val_V_2_6_0_fu_142 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_2_out;
        bayerWindow_val_V_2_7_0_fu_146 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_3_out;
        bayerWindow_val_V_2_8_0_fu_150 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_4_out;
        bayerWindow_val_V_2_9_0_fu_154 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_2_5_1_out;
        bayerWindow_val_V_3_4_0_fu_158 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_0_out;
        bayerWindow_val_V_3_5_0_fu_162 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_1_out;
        bayerWindow_val_V_3_6_0_fu_166 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_2_out;
        bayerWindow_val_V_3_7_0_fu_170 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_3_out;
        bayerWindow_val_V_3_8_0_fu_174 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_4_out;
        bayerWindow_val_V_3_9_0_fu_178 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_3_5_1_out;
        bayerWindow_val_V_4_4_0_fu_182 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_0_out;
        bayerWindow_val_V_4_5_0_fu_186 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_1_out;
        bayerWindow_val_V_4_6_0_fu_190 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_2_out;
        bayerWindow_val_V_4_7_0_fu_194 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_3_out;
        bayerWindow_val_V_4_8_0_fu_198 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_4_out;
        bayerWindow_val_V_4_9_0_fu_202 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_bayerWindow_val_V_4_5_1_out;
        pixBuf_val_V_0_0_0_fu_206 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_0_1_out;
        pixBuf_val_V_0_1_0_fu_210 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_1_1_out;
        pixBuf_val_V_0_2_0_fu_214 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_2_1_out;
        pixBuf_val_V_0_3_0_fu_218 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_0_3_1_out;
        pixBuf_val_V_1_0_01817_fu_222 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_0_1_out;
        pixBuf_val_V_1_1_01818_fu_226 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_1_1_out;
        pixBuf_val_V_1_2_01819_fu_230 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_2_1_out;
        pixBuf_val_V_1_3_01820_fu_234 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_1_3_1_out;
        pixBuf_val_V_2_0_01821_fu_238 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_0_1_out;
        pixBuf_val_V_2_1_01822_fu_242 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_1_1_out;
        pixBuf_val_V_2_2_01823_fu_246 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_2_1_out;
        pixBuf_val_V_2_3_01824_fu_250 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_2_3_1_out;
        pixBuf_val_V_3_0_01825_fu_254 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_0_1_out;
        pixBuf_val_V_3_1_01826_fu_258 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_1_1_out;
        pixBuf_val_V_3_2_01827_fu_262 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_2_1_out;
        pixBuf_val_V_3_3_01828_fu_266 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_3_3_1_out;
        pixBuf_val_V_4_0_01829_fu_270 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_0_1_out;
        pixBuf_val_V_4_1_01830_fu_274 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_1_1_out;
        pixBuf_val_V_4_2_01831_fu_278 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_2_1_out;
        pixBuf_val_V_4_3_01832_fu_282 <= grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_pixBuf_val_V_4_3_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln266_fu_724_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        cmp101_reg_2202 <= cmp101_fu_967_p2;
        cmp47_reg_2197 <= cmp47_fu_961_p2;
        cmp610_reg_2192 <= cmp610_fu_955_p2;
        icmp_ln390_1_reg_2212 <= icmp_ln390_1_fu_980_p2;
        icmp_ln390_reg_2207 <= icmp_ln390_fu_974_p2;
        out_y_reg_2187 <= out_y_fu_939_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln244_1_reg_2013 <= {{p_read[15:1]}};
        zext_ln245_reg_2019[0] <= zext_ln245_fu_680_p1[0];
        zext_ln390_reg_2029[0] <= zext_ln390_fu_712_p1[0];
    end
end

always @ (*) begin
    if (((bayerPhase_c9_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln266_fu_724_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c9_blk_n = bayerPhase_c9_full_n;
    end else begin
        bayerPhase_c9_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((bayerPhase_c9_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c9_write = 1'b1;
    end else begin
        bayerPhase_c9_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgBayer_read = grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_imgBayer_read;
    end else begin
        imgBayer_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgG_write = grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_imgG_write;
    end else begin
        imgG_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln266_fu_724_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((bayerPhase_c9_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln266_fu_724_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln266_fu_684_p2 = (zext_ln234_fu_662_p1 + 17'd3);

assign and161_cast_fu_946_p1 = empty_196_fu_935_p1;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((bayerPhase_c9_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign bayerPhase_c9_din = p_read;

assign cmp101_fu_967_p2 = ((y_fu_82 != 17'd0) ? 1'b1 : 1'b0);

assign cmp47_fu_961_p2 = ((y_fu_82 < zext_ln225_fu_652_p1) ? 1'b1 : 1'b0);

assign cmp610_fu_955_p2 = ((and161_cast_fu_946_p1 == trunc_ln244_1_reg_2013) ? 1'b1 : 1'b0);

assign empty_196_fu_935_p1 = y_fu_82[0:0];

assign grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_add_ln266_1 = (trunc_ln_fu_690_p4 + 15'd1);

assign grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_start = grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_ap_start_reg;

assign icmp_ln266_fu_724_p2 = ((y_fu_82 == loopHeight_fu_656_p2) ? 1'b1 : 1'b0);

assign icmp_ln390_1_fu_980_p2 = ((xor_fu_950_p2 == zext_ln390_reg_2029) ? 1'b1 : 1'b0);

assign icmp_ln390_fu_974_p2 = ((xor_fu_950_p2 == zext_ln245_reg_2019) ? 1'b1 : 1'b0);

assign imgG_din = grp_DebayerG_Pipeline_VITIS_LOOP_269_4_fu_528_imgG_din;

assign loopHeight_fu_656_p2 = (zext_ln225_fu_652_p1 + 17'd2);

assign out_y_fu_939_p2 = ($signed(y_fu_82) + $signed(17'd131070));

assign start_out = real_start;

assign trunc_ln_fu_690_p4 = {{add_ln266_fu_684_p2[16:2]}};

assign x_phase_fu_666_p1 = p_read[0:0];

assign xor_fu_950_p2 = (trunc_ln244_1_reg_2013 ^ and161_cast_fu_946_p1);

assign xor_ln390_fu_706_p2 = (x_phase_fu_666_p1 ^ 1'd1);

assign y_8_fu_729_p2 = (y_fu_82 + 17'd1);

assign zext_ln225_fu_652_p1 = height;

assign zext_ln234_fu_662_p1 = width;

assign zext_ln245_fu_680_p1 = x_phase_fu_666_p1;

assign zext_ln390_fu_712_p1 = xor_ln390_fu_706_p2;

always @ (posedge ap_clk) begin
    zext_ln245_reg_2019[14:1] <= 14'b00000000000000;
    zext_ln390_reg_2029[14:1] <= 14'b00000000000000;
end

endmodule //design_0_v_demosaic_0_0_DebayerG
