// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_0_v_demosaic_0_0_DebayerRandBatG (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        imgRB_dout,
        imgRB_empty_n,
        imgRB_read,
        imgRgb_din,
        imgRgb_full_n,
        imgRgb_write,
        height,
        width,
        bayerPhase_c_dout,
        bayerPhase_c_empty_n,
        bayerPhase_c_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [95:0] imgRB_dout;
input   imgRB_empty_n;
output   imgRB_read;
output  [95:0] imgRgb_din;
input   imgRgb_full_n;
output   imgRgb_write;
input  [11:0] height;
input  [11:0] width;
input  [15:0] bayerPhase_c_dout;
input   bayerPhase_c_empty_n;
output   bayerPhase_c_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg imgRB_read;
reg imgRgb_write;
reg bayerPhase_c_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    bayerPhase_c_blk_n;
wire   [11:0] loopHeight_fu_871_p2;
reg   [14:0] trunc_ln822_1_i_reg_2842;
wire   [14:0] zext_ln823_fu_891_p1;
reg   [14:0] zext_ln823_reg_2847;
wire   [14:0] zext_ln966_fu_923_p1;
reg   [14:0] zext_ln966_reg_2857;
wire   [12:0] out_y_i_fu_1254_p2;
reg   [12:0] out_y_i_reg_3090;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln830_fu_939_p2;
wire   [0:0] cmp37_i_fu_1276_p2;
reg   [0:0] cmp37_i_reg_3095;
wire   [0:0] cmp140_i_fu_1282_p2;
reg   [0:0] cmp140_i_reg_3100;
wire   [0:0] icmp_ln966_fu_1289_p2;
reg   [0:0] icmp_ln966_reg_3105;
wire   [0:0] icmp_ln966_1_fu_1295_p2;
reg   [0:0] icmp_ln966_1_reg_3110;
wire   [0:0] xor_ln966_1_fu_1301_p2;
reg   [0:0] xor_ln966_1_reg_3115;
wire   [0:0] xor_ln966_2_fu_1308_p2;
reg   [0:0] xor_ln966_2_reg_3120;
wire   [95:0] lineBuffer_val_V_0_q1;
wire   [95:0] lineBuffer_val_V_1_q1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_start;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_done;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_idle;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_ready;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_imgRB_read;
wire   [95:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_imgRgb_din;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_imgRgb_write;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_add_ln830_1_i;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_address0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_ce0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_we0;
wire   [95:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_d0;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_address1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_ce1;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_address0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_ce0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_we0;
wire   [95:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_d0;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_address1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_ce1;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_11_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_11_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_10_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_10_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_9_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_9_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_8_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_8_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_7_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_7_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_6_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_6_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_5_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_5_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_4_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_4_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_3_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_3_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_2_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_1_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_0_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_0_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_11_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_11_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_10_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_10_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_9_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_9_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_8_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_8_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_7_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_7_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_6_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_6_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_5_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_5_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_4_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_4_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_3_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_3_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_2_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_1_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_0_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_0_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_11_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_11_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_10_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_10_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_9_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_9_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_8_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_8_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_7_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_7_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_6_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_6_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_5_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_5_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_4_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_4_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_3_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_3_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_2_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_1_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_0_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_0_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_2_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_2_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_1_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_1_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_0_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_0_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_0_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_0_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_0_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_2_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_2_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_1_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_1_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_0_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_0_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_0_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_0_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_0_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_0_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_2_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_2_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_1_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_1_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_0_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_0_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_0_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_0_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_0_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_2_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_1_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_0_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_0_i_out_ap_vld;
reg    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [11:0] y_fu_72;
wire   [11:0] y_6_fu_944_p2;
reg    ap_block_state1;
reg   [7:0] pixWindow_val_val_V_0_5_0_0_i_fu_76;
wire    ap_CS_fsm_state4;
reg   [7:0] pixWindow_val_val_V_0_5_1_0_i_fu_80;
reg   [7:0] pixWindow_val_val_V_0_5_2_0_i_fu_84;
reg   [7:0] pixWindow_val_val_V_0_6_0_0_i_fu_88;
reg   [7:0] pixWindow_val_val_V_0_6_1_0_i_fu_92;
reg   [7:0] pixWindow_val_val_V_0_6_2_0_i_fu_96;
reg   [7:0] pixWindow_val_val_V_0_7_0_0_i_fu_100;
reg   [7:0] pixWindow_val_val_V_0_7_1_0_i_fu_104;
reg   [7:0] pixWindow_val_val_V_0_7_2_0_i_fu_108;
reg   [7:0] pixWindow_val_val_V_0_8_0_0_i_fu_112;
reg   [7:0] pixWindow_val_val_V_0_8_1_0_i_fu_116;
reg   [7:0] pixWindow_val_val_V_0_8_2_0_i_fu_120;
reg   [7:0] pixWindow_val_val_V_1_4_0_0_i_fu_124;
reg   [7:0] pixWindow_val_val_V_1_4_1_0_i_fu_128;
reg   [7:0] pixWindow_val_val_V_1_4_2_0_i_fu_132;
reg   [7:0] pixWindow_val_val_V_1_5_0_0_i_fu_136;
reg   [7:0] pixWindow_val_val_V_1_5_1_0_i_fu_140;
reg   [7:0] pixWindow_val_val_V_1_5_2_0_i_fu_144;
reg   [7:0] pixWindow_val_val_V_1_6_0_0_i_fu_148;
reg   [7:0] pixWindow_val_val_V_1_6_1_0_i_fu_152;
reg   [7:0] pixWindow_val_val_V_1_6_2_0_i_fu_156;
reg   [7:0] pixWindow_val_val_V_1_7_0_0_i_fu_160;
reg   [7:0] pixWindow_val_val_V_1_7_1_0_i_fu_164;
reg   [7:0] pixWindow_val_val_V_1_7_2_0_i_fu_168;
reg   [7:0] pixWindow_val_val_V_1_8_0_0_i_fu_172;
reg   [7:0] pixWindow_val_val_V_1_8_1_0_i_fu_176;
reg   [7:0] pixWindow_val_val_V_1_8_2_0_i_fu_180;
reg   [7:0] pixWindow_val_val_V_2_5_0_0_i_fu_184;
reg   [7:0] pixWindow_val_val_V_2_5_1_0_i_fu_188;
reg   [7:0] pixWindow_val_val_V_2_5_2_0_i_fu_192;
reg   [7:0] pixWindow_val_val_V_2_6_0_0_i_fu_196;
reg   [7:0] pixWindow_val_val_V_2_6_1_0_i_fu_200;
reg   [7:0] pixWindow_val_val_V_2_6_2_0_i_fu_204;
reg   [7:0] pixWindow_val_val_V_2_7_0_0_i_fu_208;
reg   [7:0] pixWindow_val_val_V_2_7_1_0_i_fu_212;
reg   [7:0] pixWindow_val_val_V_2_7_2_0_i_fu_216;
reg   [7:0] pixWindow_val_val_V_2_8_0_0_i_fu_220;
reg   [7:0] pixWindow_val_val_V_2_8_1_0_i_fu_224;
reg   [7:0] pixWindow_val_val_V_2_8_2_0_i_fu_228;
reg   [7:0] pixBuf_val_V_0_0_0_i_fu_232;
reg   [7:0] pixBuf_val_V_0_1_0_i_fu_236;
reg   [7:0] pixBuf_val_V_0_2_0_i_fu_240;
reg   [7:0] pixBuf_val_V_0_3_0_i_fu_244;
reg   [7:0] pixBuf_val_V_0_4_0_i_fu_248;
reg   [7:0] pixBuf_val_V_0_5_0_i_fu_252;
reg   [7:0] pixBuf_val_V_0_6_0_i_fu_256;
reg   [7:0] pixBuf_val_V_0_7_0_i_fu_260;
reg   [7:0] pixBuf_val_V_0_8_0_i_fu_264;
reg   [7:0] pixBuf_val_V_0_9_0_i_fu_268;
reg   [7:0] pixBuf_val_V_0_10_0_i_fu_272;
reg   [7:0] pixBuf_val_V_0_11_0_i_fu_276;
reg   [7:0] pixBuf_val_V_1_0_03134_i_fu_280;
reg   [7:0] pixBuf_val_V_1_1_03135_i_fu_284;
reg   [7:0] pixBuf_val_V_1_2_03136_i_fu_288;
reg   [7:0] pixBuf_val_V_1_3_03137_i_fu_292;
reg   [7:0] pixBuf_val_V_1_4_03138_i_fu_296;
reg   [7:0] pixBuf_val_V_1_5_03139_i_fu_300;
reg   [7:0] pixBuf_val_V_1_6_03140_i_fu_304;
reg   [7:0] pixBuf_val_V_1_7_03141_i_fu_308;
reg   [7:0] pixBuf_val_V_1_8_03142_i_fu_312;
reg   [7:0] pixBuf_val_V_1_9_03143_i_fu_316;
reg   [7:0] pixBuf_val_V_1_10_03144_i_fu_320;
reg   [7:0] pixBuf_val_V_1_11_03145_i_fu_324;
reg   [7:0] pixBuf_val_V_2_0_03146_i_fu_328;
reg   [7:0] pixBuf_val_V_2_1_03147_i_fu_332;
reg   [7:0] pixBuf_val_V_2_2_03148_i_fu_336;
reg   [7:0] pixBuf_val_V_2_3_03149_i_fu_340;
reg   [7:0] pixBuf_val_V_2_4_03150_i_fu_344;
reg   [7:0] pixBuf_val_V_2_5_03151_i_fu_348;
reg   [7:0] pixBuf_val_V_2_6_03152_i_fu_352;
reg   [7:0] pixBuf_val_V_2_7_03153_i_fu_356;
reg   [7:0] pixBuf_val_V_2_8_03154_i_fu_360;
reg   [7:0] pixBuf_val_V_2_9_03155_i_fu_364;
reg   [7:0] pixBuf_val_V_2_10_03156_i_fu_368;
reg   [7:0] pixBuf_val_V_2_11_03157_i_fu_372;
wire   [0:0] x_phase_fu_877_p1;
wire   [11:0] add_ln830_fu_895_p2;
wire   [9:0] trunc_ln_i_fu_901_p4;
wire   [0:0] xor_ln966_fu_917_p2;
wire   [12:0] zext_ln830_fu_935_p1;
wire   [0:0] empty_184_fu_1250_p1;
wire   [0:0] out_y_cast_i_fu_1261_p2;
wire   [14:0] and215_cast_i_fu_1267_p1;
wire   [14:0] xor_i_fu_1271_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_start_reg = 1'b0;
end

design_0_v_demosaic_0_0_DebayerRandBatG_lineBuffer_val_V_0 #(
    .DataWidth( 96 ),
    .AddressRange( 961 ),
    .AddressWidth( 10 ))
lineBuffer_val_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_address0),
    .ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_ce0),
    .we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_we0),
    .d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_d0),
    .address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_address1),
    .ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_ce1),
    .q1(lineBuffer_val_V_0_q1)
);

design_0_v_demosaic_0_0_DebayerRandBatG_lineBuffer_val_V_0 #(
    .DataWidth( 96 ),
    .AddressRange( 961 ),
    .AddressWidth( 10 ))
lineBuffer_val_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_address0),
    .ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_ce0),
    .we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_we0),
    .d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_d0),
    .address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_address1),
    .ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_ce1),
    .q1(lineBuffer_val_V_1_q1)
);

design_0_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2 grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_start),
    .ap_done(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_done),
    .ap_idle(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_idle),
    .ap_ready(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_ready),
    .imgRB_dout(imgRB_dout),
    .imgRB_empty_n(imgRB_empty_n),
    .imgRB_read(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_imgRB_read),
    .imgRgb_din(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_imgRgb_din),
    .imgRgb_full_n(imgRgb_full_n),
    .imgRgb_write(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_imgRgb_write),
    .pixBuf_val_V_2_11_03157_i(pixBuf_val_V_2_11_03157_i_fu_372),
    .pixBuf_val_V_2_10_03156_i(pixBuf_val_V_2_10_03156_i_fu_368),
    .pixBuf_val_V_2_9_03155_i(pixBuf_val_V_2_9_03155_i_fu_364),
    .pixBuf_val_V_2_8_03154_i(pixBuf_val_V_2_8_03154_i_fu_360),
    .pixBuf_val_V_2_7_03153_i(pixBuf_val_V_2_7_03153_i_fu_356),
    .pixBuf_val_V_2_6_03152_i(pixBuf_val_V_2_6_03152_i_fu_352),
    .pixBuf_val_V_2_5_03151_i(pixBuf_val_V_2_5_03151_i_fu_348),
    .pixBuf_val_V_2_4_03150_i(pixBuf_val_V_2_4_03150_i_fu_344),
    .pixBuf_val_V_2_3_03149_i(pixBuf_val_V_2_3_03149_i_fu_340),
    .pixBuf_val_V_2_2_03148_i(pixBuf_val_V_2_2_03148_i_fu_336),
    .pixBuf_val_V_2_1_03147_i(pixBuf_val_V_2_1_03147_i_fu_332),
    .pixBuf_val_V_2_0_03146_i(pixBuf_val_V_2_0_03146_i_fu_328),
    .pixBuf_val_V_1_11_03145_i(pixBuf_val_V_1_11_03145_i_fu_324),
    .pixBuf_val_V_1_10_03144_i(pixBuf_val_V_1_10_03144_i_fu_320),
    .pixBuf_val_V_1_9_03143_i(pixBuf_val_V_1_9_03143_i_fu_316),
    .pixBuf_val_V_1_8_03142_i(pixBuf_val_V_1_8_03142_i_fu_312),
    .pixBuf_val_V_1_7_03141_i(pixBuf_val_V_1_7_03141_i_fu_308),
    .pixBuf_val_V_1_6_03140_i(pixBuf_val_V_1_6_03140_i_fu_304),
    .pixBuf_val_V_1_5_03139_i(pixBuf_val_V_1_5_03139_i_fu_300),
    .pixBuf_val_V_1_4_03138_i(pixBuf_val_V_1_4_03138_i_fu_296),
    .pixBuf_val_V_1_3_03137_i(pixBuf_val_V_1_3_03137_i_fu_292),
    .pixBuf_val_V_1_2_03136_i(pixBuf_val_V_1_2_03136_i_fu_288),
    .pixBuf_val_V_1_1_03135_i(pixBuf_val_V_1_1_03135_i_fu_284),
    .pixBuf_val_V_1_0_03134_i(pixBuf_val_V_1_0_03134_i_fu_280),
    .pixBuf_val_V_0_11_0_i(pixBuf_val_V_0_11_0_i_fu_276),
    .pixBuf_val_V_0_10_0_i(pixBuf_val_V_0_10_0_i_fu_272),
    .pixBuf_val_V_0_9_0_i(pixBuf_val_V_0_9_0_i_fu_268),
    .pixBuf_val_V_0_8_0_i(pixBuf_val_V_0_8_0_i_fu_264),
    .pixBuf_val_V_0_7_0_i(pixBuf_val_V_0_7_0_i_fu_260),
    .pixBuf_val_V_0_6_0_i(pixBuf_val_V_0_6_0_i_fu_256),
    .pixBuf_val_V_0_5_0_i(pixBuf_val_V_0_5_0_i_fu_252),
    .pixBuf_val_V_0_4_0_i(pixBuf_val_V_0_4_0_i_fu_248),
    .pixBuf_val_V_0_3_0_i(pixBuf_val_V_0_3_0_i_fu_244),
    .pixBuf_val_V_0_2_0_i(pixBuf_val_V_0_2_0_i_fu_240),
    .pixBuf_val_V_0_1_0_i(pixBuf_val_V_0_1_0_i_fu_236),
    .pixBuf_val_V_0_0_0_i(pixBuf_val_V_0_0_0_i_fu_232),
    .pixWindow_val_val_V_2_8_2_0_i(pixWindow_val_val_V_2_8_2_0_i_fu_228),
    .pixWindow_val_val_V_2_8_1_0_i(pixWindow_val_val_V_2_8_1_0_i_fu_224),
    .pixWindow_val_val_V_2_8_0_0_i(pixWindow_val_val_V_2_8_0_0_i_fu_220),
    .pixWindow_val_val_V_2_7_2_0_i(pixWindow_val_val_V_2_7_2_0_i_fu_216),
    .pixWindow_val_val_V_2_7_1_0_i(pixWindow_val_val_V_2_7_1_0_i_fu_212),
    .pixWindow_val_val_V_2_7_0_0_i(pixWindow_val_val_V_2_7_0_0_i_fu_208),
    .pixWindow_val_val_V_2_6_2_0_i(pixWindow_val_val_V_2_6_2_0_i_fu_204),
    .pixWindow_val_val_V_2_6_1_0_i(pixWindow_val_val_V_2_6_1_0_i_fu_200),
    .pixWindow_val_val_V_2_6_0_0_i(pixWindow_val_val_V_2_6_0_0_i_fu_196),
    .pixWindow_val_val_V_2_5_2_0_i(pixWindow_val_val_V_2_5_2_0_i_fu_192),
    .pixWindow_val_val_V_2_5_1_0_i(pixWindow_val_val_V_2_5_1_0_i_fu_188),
    .pixWindow_val_val_V_2_5_0_0_i(pixWindow_val_val_V_2_5_0_0_i_fu_184),
    .pixWindow_val_val_V_1_8_2_0_i(pixWindow_val_val_V_1_8_2_0_i_fu_180),
    .pixWindow_val_val_V_1_8_1_0_i(pixWindow_val_val_V_1_8_1_0_i_fu_176),
    .pixWindow_val_val_V_1_8_0_0_i(pixWindow_val_val_V_1_8_0_0_i_fu_172),
    .pixWindow_val_val_V_1_7_2_0_i(pixWindow_val_val_V_1_7_2_0_i_fu_168),
    .pixWindow_val_val_V_1_7_1_0_i(pixWindow_val_val_V_1_7_1_0_i_fu_164),
    .pixWindow_val_val_V_1_7_0_0_i(pixWindow_val_val_V_1_7_0_0_i_fu_160),
    .pixWindow_val_val_V_1_6_2_0_i(pixWindow_val_val_V_1_6_2_0_i_fu_156),
    .pixWindow_val_val_V_1_6_1_0_i(pixWindow_val_val_V_1_6_1_0_i_fu_152),
    .pixWindow_val_val_V_1_6_0_0_i(pixWindow_val_val_V_1_6_0_0_i_fu_148),
    .pixWindow_val_val_V_1_5_2_0_i(pixWindow_val_val_V_1_5_2_0_i_fu_144),
    .pixWindow_val_val_V_1_5_1_0_i(pixWindow_val_val_V_1_5_1_0_i_fu_140),
    .pixWindow_val_val_V_1_5_0_0_i(pixWindow_val_val_V_1_5_0_0_i_fu_136),
    .pixWindow_val_val_V_1_4_2_0_i(pixWindow_val_val_V_1_4_2_0_i_fu_132),
    .pixWindow_val_val_V_1_4_1_0_i(pixWindow_val_val_V_1_4_1_0_i_fu_128),
    .pixWindow_val_val_V_1_4_0_0_i(pixWindow_val_val_V_1_4_0_0_i_fu_124),
    .pixWindow_val_val_V_0_8_2_0_i(pixWindow_val_val_V_0_8_2_0_i_fu_120),
    .pixWindow_val_val_V_0_8_1_0_i(pixWindow_val_val_V_0_8_1_0_i_fu_116),
    .pixWindow_val_val_V_0_8_0_0_i(pixWindow_val_val_V_0_8_0_0_i_fu_112),
    .pixWindow_val_val_V_0_7_2_0_i(pixWindow_val_val_V_0_7_2_0_i_fu_108),
    .pixWindow_val_val_V_0_7_1_0_i(pixWindow_val_val_V_0_7_1_0_i_fu_104),
    .pixWindow_val_val_V_0_7_0_0_i(pixWindow_val_val_V_0_7_0_0_i_fu_100),
    .pixWindow_val_val_V_0_6_2_0_i(pixWindow_val_val_V_0_6_2_0_i_fu_96),
    .pixWindow_val_val_V_0_6_1_0_i(pixWindow_val_val_V_0_6_1_0_i_fu_92),
    .pixWindow_val_val_V_0_6_0_0_i(pixWindow_val_val_V_0_6_0_0_i_fu_88),
    .pixWindow_val_val_V_0_5_2_0_i(pixWindow_val_val_V_0_5_2_0_i_fu_84),
    .pixWindow_val_val_V_0_5_1_0_i(pixWindow_val_val_V_0_5_1_0_i_fu_80),
    .pixWindow_val_val_V_0_5_0_0_i(pixWindow_val_val_V_0_5_0_0_i_fu_76),
    .add_ln830_1_i(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_add_ln830_1_i),
    .icmp_ln966_i(icmp_ln966_reg_3105),
    .xor_ln966_1_i(xor_ln966_1_reg_3115),
    .icmp_ln966_1_i(icmp_ln966_1_reg_3110),
    .xor_ln966_2_i(xor_ln966_2_reg_3120),
    .out_y_i(out_y_i_reg_3090),
    .width_cast(width),
    .lineBuffer_val_V_0_i_address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_address0),
    .lineBuffer_val_V_0_i_ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_ce0),
    .lineBuffer_val_V_0_i_we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_we0),
    .lineBuffer_val_V_0_i_d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_d0),
    .lineBuffer_val_V_0_i_address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_address1),
    .lineBuffer_val_V_0_i_ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_0_i_ce1),
    .lineBuffer_val_V_0_i_q1(lineBuffer_val_V_0_q1),
    .lineBuffer_val_V_1_i_address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_address0),
    .lineBuffer_val_V_1_i_ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_ce0),
    .lineBuffer_val_V_1_i_we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_we0),
    .lineBuffer_val_V_1_i_d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_d0),
    .lineBuffer_val_V_1_i_address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_address1),
    .lineBuffer_val_V_1_i_ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_lineBuffer_val_V_1_i_ce1),
    .lineBuffer_val_V_1_i_q1(lineBuffer_val_V_1_q1),
    .cmp37_i(cmp37_i_reg_3095),
    .cmp140_i(cmp140_i_reg_3100),
    .pixBuf_val_V_2_11_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_11_1_i_out),
    .pixBuf_val_V_2_11_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_11_1_i_out_ap_vld),
    .pixBuf_val_V_2_10_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_10_1_i_out),
    .pixBuf_val_V_2_10_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_10_1_i_out_ap_vld),
    .pixBuf_val_V_2_9_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_9_1_i_out),
    .pixBuf_val_V_2_9_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_9_1_i_out_ap_vld),
    .pixBuf_val_V_2_8_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_8_1_i_out),
    .pixBuf_val_V_2_8_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_8_1_i_out_ap_vld),
    .pixBuf_val_V_2_7_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_7_1_i_out),
    .pixBuf_val_V_2_7_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_7_1_i_out_ap_vld),
    .pixBuf_val_V_2_6_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_6_1_i_out),
    .pixBuf_val_V_2_6_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_6_1_i_out_ap_vld),
    .pixBuf_val_V_2_5_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_5_1_i_out),
    .pixBuf_val_V_2_5_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_5_1_i_out_ap_vld),
    .pixBuf_val_V_2_4_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_4_1_i_out),
    .pixBuf_val_V_2_4_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_4_1_i_out_ap_vld),
    .pixBuf_val_V_2_3_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_3_1_i_out),
    .pixBuf_val_V_2_3_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_3_1_i_out_ap_vld),
    .pixBuf_val_V_2_2_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_2_1_i_out),
    .pixBuf_val_V_2_2_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_2_1_i_out_ap_vld),
    .pixBuf_val_V_2_1_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_1_1_i_out),
    .pixBuf_val_V_2_1_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_1_1_i_out_ap_vld),
    .pixBuf_val_V_2_0_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_0_1_i_out),
    .pixBuf_val_V_2_0_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_0_1_i_out_ap_vld),
    .pixBuf_val_V_1_11_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_11_1_i_out),
    .pixBuf_val_V_1_11_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_11_1_i_out_ap_vld),
    .pixBuf_val_V_1_10_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_10_1_i_out),
    .pixBuf_val_V_1_10_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_10_1_i_out_ap_vld),
    .pixBuf_val_V_1_9_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_9_1_i_out),
    .pixBuf_val_V_1_9_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_9_1_i_out_ap_vld),
    .pixBuf_val_V_1_8_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_8_1_i_out),
    .pixBuf_val_V_1_8_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_8_1_i_out_ap_vld),
    .pixBuf_val_V_1_7_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_7_1_i_out),
    .pixBuf_val_V_1_7_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_7_1_i_out_ap_vld),
    .pixBuf_val_V_1_6_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_6_1_i_out),
    .pixBuf_val_V_1_6_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_6_1_i_out_ap_vld),
    .pixBuf_val_V_1_5_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_5_1_i_out),
    .pixBuf_val_V_1_5_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_5_1_i_out_ap_vld),
    .pixBuf_val_V_1_4_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_4_1_i_out),
    .pixBuf_val_V_1_4_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_4_1_i_out_ap_vld),
    .pixBuf_val_V_1_3_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_3_1_i_out),
    .pixBuf_val_V_1_3_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_3_1_i_out_ap_vld),
    .pixBuf_val_V_1_2_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_2_1_i_out),
    .pixBuf_val_V_1_2_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_2_1_i_out_ap_vld),
    .pixBuf_val_V_1_1_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_1_1_i_out),
    .pixBuf_val_V_1_1_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_1_1_i_out_ap_vld),
    .pixBuf_val_V_1_0_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_0_1_i_out),
    .pixBuf_val_V_1_0_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_0_1_i_out_ap_vld),
    .pixBuf_val_V_0_11_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_11_1_i_out),
    .pixBuf_val_V_0_11_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_11_1_i_out_ap_vld),
    .pixBuf_val_V_0_10_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_10_1_i_out),
    .pixBuf_val_V_0_10_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_10_1_i_out_ap_vld),
    .pixBuf_val_V_0_9_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_9_1_i_out),
    .pixBuf_val_V_0_9_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_9_1_i_out_ap_vld),
    .pixBuf_val_V_0_8_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_8_1_i_out),
    .pixBuf_val_V_0_8_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_8_1_i_out_ap_vld),
    .pixBuf_val_V_0_7_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_7_1_i_out),
    .pixBuf_val_V_0_7_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_7_1_i_out_ap_vld),
    .pixBuf_val_V_0_6_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_6_1_i_out),
    .pixBuf_val_V_0_6_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_6_1_i_out_ap_vld),
    .pixBuf_val_V_0_5_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_5_1_i_out),
    .pixBuf_val_V_0_5_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_5_1_i_out_ap_vld),
    .pixBuf_val_V_0_4_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_4_1_i_out),
    .pixBuf_val_V_0_4_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_4_1_i_out_ap_vld),
    .pixBuf_val_V_0_3_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_3_1_i_out),
    .pixBuf_val_V_0_3_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_3_1_i_out_ap_vld),
    .pixBuf_val_V_0_2_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_2_1_i_out),
    .pixBuf_val_V_0_2_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_2_1_i_out_ap_vld),
    .pixBuf_val_V_0_1_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_1_1_i_out),
    .pixBuf_val_V_0_1_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_1_1_i_out_ap_vld),
    .pixBuf_val_V_0_0_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_0_1_i_out),
    .pixBuf_val_V_0_0_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_4_2_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_2_2_i_out),
    .pixWindow_val_val_V_2_4_2_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_2_2_i_out_ap_vld),
    .pixWindow_val_val_V_2_4_1_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_1_2_i_out),
    .pixWindow_val_val_V_2_4_1_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_1_2_i_out_ap_vld),
    .pixWindow_val_val_V_2_4_0_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_0_2_i_out),
    .pixWindow_val_val_V_2_4_0_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_0_2_i_out_ap_vld),
    .pixWindow_val_val_V_2_3_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_2_i_out),
    .pixWindow_val_val_V_2_3_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_2_i_out_ap_vld),
    .pixWindow_val_val_V_2_3_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_1_i_out),
    .pixWindow_val_val_V_2_3_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_3_0_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_0_i_out),
    .pixWindow_val_val_V_2_3_0_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_0_i_out_ap_vld),
    .pixWindow_val_val_V_2_2_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_2_i_out),
    .pixWindow_val_val_V_2_2_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_2_i_out_ap_vld),
    .pixWindow_val_val_V_2_2_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_1_i_out),
    .pixWindow_val_val_V_2_2_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_2_0_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_0_i_out),
    .pixWindow_val_val_V_2_2_0_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_0_i_out_ap_vld),
    .pixWindow_val_val_V_2_1_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_2_i_out),
    .pixWindow_val_val_V_2_1_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_2_i_out_ap_vld),
    .pixWindow_val_val_V_2_1_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_1_i_out),
    .pixWindow_val_val_V_2_1_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_1_0_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_0_i_out),
    .pixWindow_val_val_V_2_1_0_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_0_i_out_ap_vld),
    .pixWindow_val_val_V_1_4_2_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_2_2_i_out),
    .pixWindow_val_val_V_1_4_2_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_2_2_i_out_ap_vld),
    .pixWindow_val_val_V_1_4_1_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_1_2_i_out),
    .pixWindow_val_val_V_1_4_1_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_1_2_i_out_ap_vld),
    .pixWindow_val_val_V_1_4_0_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_0_2_i_out),
    .pixWindow_val_val_V_1_4_0_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_0_2_i_out_ap_vld),
    .pixWindow_val_val_V_1_3_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_2_i_out),
    .pixWindow_val_val_V_1_3_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_2_i_out_ap_vld),
    .pixWindow_val_val_V_1_3_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_1_i_out),
    .pixWindow_val_val_V_1_3_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_1_i_out_ap_vld),
    .pixWindow_val_val_V_1_3_0_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_0_i_out),
    .pixWindow_val_val_V_1_3_0_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_0_i_out_ap_vld),
    .pixWindow_val_val_V_1_2_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_2_i_out),
    .pixWindow_val_val_V_1_2_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_2_i_out_ap_vld),
    .pixWindow_val_val_V_1_2_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_1_i_out),
    .pixWindow_val_val_V_1_2_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_1_i_out_ap_vld),
    .pixWindow_val_val_V_1_2_0_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_0_i_out),
    .pixWindow_val_val_V_1_2_0_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_0_i_out_ap_vld),
    .pixWindow_val_val_V_1_1_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_2_i_out),
    .pixWindow_val_val_V_1_1_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_2_i_out_ap_vld),
    .pixWindow_val_val_V_1_1_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_1_i_out),
    .pixWindow_val_val_V_1_1_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_1_i_out_ap_vld),
    .pixWindow_val_val_V_1_1_0_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_0_i_out),
    .pixWindow_val_val_V_1_1_0_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_0_i_out_ap_vld),
    .pixWindow_val_val_V_1_0_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_2_i_out),
    .pixWindow_val_val_V_1_0_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_2_i_out_ap_vld),
    .pixWindow_val_val_V_1_0_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_1_i_out),
    .pixWindow_val_val_V_1_0_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_1_0_0_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_0_i_out),
    .pixWindow_val_val_V_1_0_0_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_0_i_out_ap_vld),
    .pixWindow_val_val_V_0_4_2_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_2_2_i_out),
    .pixWindow_val_val_V_0_4_2_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_2_2_i_out_ap_vld),
    .pixWindow_val_val_V_0_4_1_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_1_2_i_out),
    .pixWindow_val_val_V_0_4_1_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_1_2_i_out_ap_vld),
    .pixWindow_val_val_V_0_4_0_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_0_2_i_out),
    .pixWindow_val_val_V_0_4_0_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_0_2_i_out_ap_vld),
    .pixWindow_val_val_V_0_3_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_2_i_out),
    .pixWindow_val_val_V_0_3_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_2_i_out_ap_vld),
    .pixWindow_val_val_V_0_3_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_1_i_out),
    .pixWindow_val_val_V_0_3_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_1_i_out_ap_vld),
    .pixWindow_val_val_V_0_3_0_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_0_i_out),
    .pixWindow_val_val_V_0_3_0_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_0_i_out_ap_vld),
    .pixWindow_val_val_V_0_2_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_2_i_out),
    .pixWindow_val_val_V_0_2_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_2_i_out_ap_vld),
    .pixWindow_val_val_V_0_2_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_1_i_out),
    .pixWindow_val_val_V_0_2_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_1_i_out_ap_vld),
    .pixWindow_val_val_V_0_2_0_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_0_i_out),
    .pixWindow_val_val_V_0_2_0_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_0_i_out_ap_vld),
    .pixWindow_val_val_V_0_1_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_2_i_out),
    .pixWindow_val_val_V_0_1_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_2_i_out_ap_vld),
    .pixWindow_val_val_V_0_1_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_1_i_out),
    .pixWindow_val_val_V_0_1_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_1_i_out_ap_vld),
    .pixWindow_val_val_V_0_1_0_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_0_i_out),
    .pixWindow_val_val_V_0_1_0_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_0_i_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln830_fu_939_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln830_fu_939_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_start_reg <= 1'b1;
        end else if ((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_ready == 1'b1)) begin
            grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_72 <= 12'd0;
    end else if (((icmp_ln830_fu_939_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_72 <= y_6_fu_944_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln830_fu_939_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        cmp140_i_reg_3100 <= cmp140_i_fu_1282_p2;
        cmp37_i_reg_3095 <= cmp37_i_fu_1276_p2;
        icmp_ln966_1_reg_3110 <= icmp_ln966_1_fu_1295_p2;
        icmp_ln966_reg_3105 <= icmp_ln966_fu_1289_p2;
        out_y_i_reg_3090 <= out_y_i_fu_1254_p2;
        xor_ln966_1_reg_3115 <= xor_ln966_1_fu_1301_p2;
        xor_ln966_2_reg_3120 <= xor_ln966_2_fu_1308_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pixBuf_val_V_0_0_0_i_fu_232 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_0_1_i_out;
        pixBuf_val_V_0_10_0_i_fu_272 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_10_1_i_out;
        pixBuf_val_V_0_11_0_i_fu_276 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_11_1_i_out;
        pixBuf_val_V_0_1_0_i_fu_236 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_1_1_i_out;
        pixBuf_val_V_0_2_0_i_fu_240 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_2_1_i_out;
        pixBuf_val_V_0_3_0_i_fu_244 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_3_1_i_out;
        pixBuf_val_V_0_4_0_i_fu_248 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_4_1_i_out;
        pixBuf_val_V_0_5_0_i_fu_252 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_5_1_i_out;
        pixBuf_val_V_0_6_0_i_fu_256 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_6_1_i_out;
        pixBuf_val_V_0_7_0_i_fu_260 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_7_1_i_out;
        pixBuf_val_V_0_8_0_i_fu_264 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_8_1_i_out;
        pixBuf_val_V_0_9_0_i_fu_268 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_0_9_1_i_out;
        pixBuf_val_V_1_0_03134_i_fu_280 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_0_1_i_out;
        pixBuf_val_V_1_10_03144_i_fu_320 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_10_1_i_out;
        pixBuf_val_V_1_11_03145_i_fu_324 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_11_1_i_out;
        pixBuf_val_V_1_1_03135_i_fu_284 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_1_1_i_out;
        pixBuf_val_V_1_2_03136_i_fu_288 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_2_1_i_out;
        pixBuf_val_V_1_3_03137_i_fu_292 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_3_1_i_out;
        pixBuf_val_V_1_4_03138_i_fu_296 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_4_1_i_out;
        pixBuf_val_V_1_5_03139_i_fu_300 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_5_1_i_out;
        pixBuf_val_V_1_6_03140_i_fu_304 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_6_1_i_out;
        pixBuf_val_V_1_7_03141_i_fu_308 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_7_1_i_out;
        pixBuf_val_V_1_8_03142_i_fu_312 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_8_1_i_out;
        pixBuf_val_V_1_9_03143_i_fu_316 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_1_9_1_i_out;
        pixBuf_val_V_2_0_03146_i_fu_328 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_0_1_i_out;
        pixBuf_val_V_2_10_03156_i_fu_368 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_10_1_i_out;
        pixBuf_val_V_2_11_03157_i_fu_372 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_11_1_i_out;
        pixBuf_val_V_2_1_03147_i_fu_332 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_1_1_i_out;
        pixBuf_val_V_2_2_03148_i_fu_336 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_2_1_i_out;
        pixBuf_val_V_2_3_03149_i_fu_340 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_3_1_i_out;
        pixBuf_val_V_2_4_03150_i_fu_344 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_4_1_i_out;
        pixBuf_val_V_2_5_03151_i_fu_348 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_5_1_i_out;
        pixBuf_val_V_2_6_03152_i_fu_352 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_6_1_i_out;
        pixBuf_val_V_2_7_03153_i_fu_356 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_7_1_i_out;
        pixBuf_val_V_2_8_03154_i_fu_360 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_8_1_i_out;
        pixBuf_val_V_2_9_03155_i_fu_364 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixBuf_val_V_2_9_1_i_out;
        pixWindow_val_val_V_0_5_0_0_i_fu_76 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_0_i_out;
        pixWindow_val_val_V_0_5_1_0_i_fu_80 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_1_i_out;
        pixWindow_val_val_V_0_5_2_0_i_fu_84 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_1_2_i_out;
        pixWindow_val_val_V_0_6_0_0_i_fu_88 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_0_i_out;
        pixWindow_val_val_V_0_6_1_0_i_fu_92 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_1_i_out;
        pixWindow_val_val_V_0_6_2_0_i_fu_96 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_2_2_i_out;
        pixWindow_val_val_V_0_7_0_0_i_fu_100 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_0_i_out;
        pixWindow_val_val_V_0_7_1_0_i_fu_104 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_1_i_out;
        pixWindow_val_val_V_0_7_2_0_i_fu_108 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_3_2_i_out;
        pixWindow_val_val_V_0_8_0_0_i_fu_112 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_0_2_i_out;
        pixWindow_val_val_V_0_8_1_0_i_fu_116 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_1_2_i_out;
        pixWindow_val_val_V_0_8_2_0_i_fu_120 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_0_4_2_2_i_out;
        pixWindow_val_val_V_1_4_0_0_i_fu_124 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_0_i_out;
        pixWindow_val_val_V_1_4_1_0_i_fu_128 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_1_i_out;
        pixWindow_val_val_V_1_4_2_0_i_fu_132 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_0_2_i_out;
        pixWindow_val_val_V_1_5_0_0_i_fu_136 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_0_i_out;
        pixWindow_val_val_V_1_5_1_0_i_fu_140 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_1_i_out;
        pixWindow_val_val_V_1_5_2_0_i_fu_144 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_1_2_i_out;
        pixWindow_val_val_V_1_6_0_0_i_fu_148 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_0_i_out;
        pixWindow_val_val_V_1_6_1_0_i_fu_152 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_1_i_out;
        pixWindow_val_val_V_1_6_2_0_i_fu_156 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_2_2_i_out;
        pixWindow_val_val_V_1_7_0_0_i_fu_160 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_0_i_out;
        pixWindow_val_val_V_1_7_1_0_i_fu_164 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_1_i_out;
        pixWindow_val_val_V_1_7_2_0_i_fu_168 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_3_2_i_out;
        pixWindow_val_val_V_1_8_0_0_i_fu_172 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_0_2_i_out;
        pixWindow_val_val_V_1_8_1_0_i_fu_176 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_1_2_i_out;
        pixWindow_val_val_V_1_8_2_0_i_fu_180 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_1_4_2_2_i_out;
        pixWindow_val_val_V_2_5_0_0_i_fu_184 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_0_i_out;
        pixWindow_val_val_V_2_5_1_0_i_fu_188 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_1_i_out;
        pixWindow_val_val_V_2_5_2_0_i_fu_192 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_1_2_i_out;
        pixWindow_val_val_V_2_6_0_0_i_fu_196 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_0_i_out;
        pixWindow_val_val_V_2_6_1_0_i_fu_200 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_1_i_out;
        pixWindow_val_val_V_2_6_2_0_i_fu_204 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_2_2_i_out;
        pixWindow_val_val_V_2_7_0_0_i_fu_208 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_0_i_out;
        pixWindow_val_val_V_2_7_1_0_i_fu_212 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_1_i_out;
        pixWindow_val_val_V_2_7_2_0_i_fu_216 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_3_2_i_out;
        pixWindow_val_val_V_2_8_0_0_i_fu_220 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_0_2_i_out;
        pixWindow_val_val_V_2_8_1_0_i_fu_224 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_1_2_i_out;
        pixWindow_val_val_V_2_8_2_0_i_fu_228 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_pixWindow_val_val_V_2_4_2_2_i_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln822_1_i_reg_2842 <= {{bayerPhase_c_dout[15:1]}};
        zext_ln823_reg_2847[0] <= zext_ln823_fu_891_p1[0];
        zext_ln966_reg_2857[0] <= zext_ln966_fu_923_p1[0];
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln830_fu_939_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln830_fu_939_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c_blk_n = bayerPhase_c_empty_n;
    end else begin
        bayerPhase_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c_read = 1'b1;
    end else begin
        bayerPhase_c_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgRB_read = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_imgRB_read;
    end else begin
        imgRB_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgRgb_write = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_imgRgb_write;
    end else begin
        imgRgb_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln830_fu_939_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln830_fu_895_p2 = (width + 12'd3);

assign and215_cast_i_fu_1267_p1 = out_y_cast_i_fu_1261_p2;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign cmp140_i_fu_1282_p2 = ((y_fu_72 != 12'd0) ? 1'b1 : 1'b0);

assign cmp37_i_fu_1276_p2 = ((y_fu_72 < height) ? 1'b1 : 1'b0);

assign empty_184_fu_1250_p1 = y_fu_72[0:0];

assign grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_add_ln830_1_i = (trunc_ln_i_fu_901_p4 + 10'd1);

assign grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_start = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_ap_start_reg;

assign icmp_ln830_fu_939_p2 = ((y_fu_72 == loopHeight_fu_871_p2) ? 1'b1 : 1'b0);

assign icmp_ln966_1_fu_1295_p2 = ((xor_i_fu_1271_p2 == zext_ln966_reg_2857) ? 1'b1 : 1'b0);

assign icmp_ln966_fu_1289_p2 = ((xor_i_fu_1271_p2 == zext_ln823_reg_2847) ? 1'b1 : 1'b0);

assign imgRgb_din = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_702_imgRgb_din;

assign loopHeight_fu_871_p2 = (height + 12'd1);

assign out_y_cast_i_fu_1261_p2 = (empty_184_fu_1250_p1 ^ 1'd1);

assign out_y_i_fu_1254_p2 = ($signed(zext_ln830_fu_935_p1) + $signed(13'd8191));

assign trunc_ln_i_fu_901_p4 = {{add_ln830_fu_895_p2[11:2]}};

assign x_phase_fu_877_p1 = bayerPhase_c_dout[0:0];

assign xor_i_fu_1271_p2 = (trunc_ln822_1_i_reg_2842 ^ and215_cast_i_fu_1267_p1);

assign xor_ln966_1_fu_1301_p2 = (icmp_ln966_fu_1289_p2 ^ 1'd1);

assign xor_ln966_2_fu_1308_p2 = (icmp_ln966_1_fu_1295_p2 ^ 1'd1);

assign xor_ln966_fu_917_p2 = (x_phase_fu_877_p1 ^ 1'd1);

assign y_6_fu_944_p2 = (y_fu_72 + 12'd1);

assign zext_ln823_fu_891_p1 = x_phase_fu_877_p1;

assign zext_ln830_fu_935_p1 = y_fu_72;

assign zext_ln966_fu_923_p1 = xor_ln966_fu_917_p2;

always @ (posedge ap_clk) begin
    zext_ln823_reg_2847[14:1] <= 14'b00000000000000;
    zext_ln966_reg_2857[14:1] <= 14'b00000000000000;
end

endmodule //design_0_v_demosaic_0_0_DebayerRandBatG
