// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_0_v_demosaic_0_0_ZipperRemoval (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        imgRgb_dout,
        imgRgb_empty_n,
        imgRgb_read,
        imgUnzip_din,
        imgUnzip_full_n,
        imgUnzip_write,
        height,
        width
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [95:0] imgRgb_dout;
input   imgRgb_empty_n;
output   imgRgb_read;
output  [95:0] imgUnzip_din;
input   imgUnzip_full_n;
output   imgUnzip_write;
input  [15:0] height;
input  [15:0] width;

reg ap_done;
reg ap_idle;
reg start_write;
reg imgRgb_read;
reg imgUnzip_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [16:0] zext_ln1035_fu_404_p1;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln1049_fu_436_p2;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_start;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_done;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_idle;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_ready;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_imgRgb_read;
wire   [95:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_imgUnzip_din;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_imgUnzip_write;
wire   [16:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_empty;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_b_V_4_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_b_V_4_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_4_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_4_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_7_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_7_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_10_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_10_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_g_V_4_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_g_V_4_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_0_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_0_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_3_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_3_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_6_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_6_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_9_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_9_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_r_V_4_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_r_V_4_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_2_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_2_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_5_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_5_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_8_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_8_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_11_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_11_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_4_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_4_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_3_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_3_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_2_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_2_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_1_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_1_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_0_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_0_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_11_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_11_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_10_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_10_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_9_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_9_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_8_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_8_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_7_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_7_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_6_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_6_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_5_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_5_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_4_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_4_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_3_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_3_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_2_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_2_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_1_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_1_1_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_0_1_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_0_1_out_ap_vld;
reg    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [15:0] y_fu_58;
wire   [15:0] y_2_fu_441_p2;
reg    ap_block_state1;
reg   [7:0] inpix_val_V_0_0705_fu_62;
wire    ap_CS_fsm_state4;
reg   [7:0] inpix_val_V_1_0706_fu_66;
reg   [7:0] inpix_val_V_2_0707_fu_70;
reg   [7:0] inpix_val_V_3_0708_fu_74;
reg   [7:0] inpix_val_V_4_0709_fu_78;
reg   [7:0] inpix_val_V_5_0710_fu_82;
reg   [7:0] inpix_val_V_6_0711_fu_86;
reg   [7:0] inpix_val_V_7_0712_fu_90;
reg   [7:0] inpix_val_V_8_0713_fu_94;
reg   [7:0] inpix_val_V_9_0714_fu_98;
reg   [7:0] inpix_val_V_10_0715_fu_102;
reg   [7:0] inpix_val_V_11_0716_fu_106;
reg   [7:0] luma_V_0_0_fu_110;
reg   [7:0] luma_V_1_0717_fu_114;
reg   [7:0] luma_V_2_0718_fu_118;
reg   [7:0] luma_V_3_0719_fu_122;
reg   [7:0] luma_V_4_0720_fu_126;
reg   [7:0] r_V_0_0_fu_130;
reg   [7:0] r_V_1_0721_fu_134;
reg   [7:0] r_V_2_0722_fu_138;
reg   [7:0] r_V_3_0723_fu_142;
reg   [7:0] r_V_4_0724_fu_146;
reg   [7:0] g_V_0_0_fu_150;
reg   [7:0] g_V_1_0725_fu_154;
reg   [7:0] g_V_2_0726_fu_158;
reg   [7:0] g_V_3_0727_fu_162;
reg   [7:0] g_V_4_0728_fu_166;
reg   [7:0] b_V_0_0_fu_170;
reg   [7:0] b_V_1_0729_fu_174;
reg   [7:0] b_V_2_0730_fu_178;
reg   [7:0] b_V_3_0731_fu_182;
reg   [7:0] b_V_4_0732_fu_186;
wire   [16:0] add_ln1051_fu_575_p2;
wire   [14:0] tmp_fu_580_p4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_start_reg = 1'b0;
end

design_0_v_demosaic_0_0_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2 grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_start),
    .ap_done(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_done),
    .ap_idle(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_idle),
    .ap_ready(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_ready),
    .imgRgb_dout(imgRgb_dout),
    .imgRgb_empty_n(imgRgb_empty_n),
    .imgRgb_read(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_imgRgb_read),
    .imgUnzip_din(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_imgUnzip_din),
    .imgUnzip_full_n(imgUnzip_full_n),
    .imgUnzip_write(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_imgUnzip_write),
    .b_V_4_0732(b_V_4_0732_fu_186),
    .b_V_3_0731(b_V_3_0731_fu_182),
    .b_V_2_0730(b_V_2_0730_fu_178),
    .b_V_1_0729(b_V_1_0729_fu_174),
    .b_V_0_0(b_V_0_0_fu_170),
    .g_V_4_0728(g_V_4_0728_fu_166),
    .g_V_3_0727(g_V_3_0727_fu_162),
    .g_V_2_0726(g_V_2_0726_fu_158),
    .g_V_1_0725(g_V_1_0725_fu_154),
    .g_V_0_0(g_V_0_0_fu_150),
    .r_V_4_0724(r_V_4_0724_fu_146),
    .r_V_3_0723(r_V_3_0723_fu_142),
    .r_V_2_0722(r_V_2_0722_fu_138),
    .r_V_1_0721(r_V_1_0721_fu_134),
    .r_V_0_0(r_V_0_0_fu_130),
    .luma_V_4_0720(luma_V_4_0720_fu_126),
    .luma_V_3_0719(luma_V_3_0719_fu_122),
    .luma_V_2_0718(luma_V_2_0718_fu_118),
    .luma_V_1_0717(luma_V_1_0717_fu_114),
    .luma_V_0_0(luma_V_0_0_fu_110),
    .inpix_val_V_11_0716(inpix_val_V_11_0716_fu_106),
    .inpix_val_V_10_0715(inpix_val_V_10_0715_fu_102),
    .inpix_val_V_9_0714(inpix_val_V_9_0714_fu_98),
    .inpix_val_V_8_0713(inpix_val_V_8_0713_fu_94),
    .inpix_val_V_7_0712(inpix_val_V_7_0712_fu_90),
    .inpix_val_V_6_0711(inpix_val_V_6_0711_fu_86),
    .inpix_val_V_5_0710(inpix_val_V_5_0710_fu_82),
    .inpix_val_V_4_0709(inpix_val_V_4_0709_fu_78),
    .inpix_val_V_3_0708(inpix_val_V_3_0708_fu_74),
    .inpix_val_V_2_0707(inpix_val_V_2_0707_fu_70),
    .inpix_val_V_1_0706(inpix_val_V_1_0706_fu_66),
    .inpix_val_V_0_0705(inpix_val_V_0_0705_fu_62),
    .empty(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_empty),
    .zext_ln1035(width),
    .b_V_4_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_b_V_4_1_out),
    .b_V_4_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_b_V_4_1_out_ap_vld),
    .outpix_val_V_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_1_out),
    .outpix_val_V_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_1_out_ap_vld),
    .outpix_val_V_4_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_4_out),
    .outpix_val_V_4_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_4_out_ap_vld),
    .outpix_val_V_7_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_7_out),
    .outpix_val_V_7_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_7_out_ap_vld),
    .outpix_val_V_10_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_10_out),
    .outpix_val_V_10_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_10_out_ap_vld),
    .g_V_4_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_g_V_4_1_out),
    .g_V_4_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_g_V_4_1_out_ap_vld),
    .outpix_val_V_0_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_0_out),
    .outpix_val_V_0_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_0_out_ap_vld),
    .outpix_val_V_3_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_3_out),
    .outpix_val_V_3_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_3_out_ap_vld),
    .outpix_val_V_6_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_6_out),
    .outpix_val_V_6_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_6_out_ap_vld),
    .outpix_val_V_9_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_9_out),
    .outpix_val_V_9_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_9_out_ap_vld),
    .r_V_4_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_r_V_4_1_out),
    .r_V_4_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_r_V_4_1_out_ap_vld),
    .outpix_val_V_2_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_2_out),
    .outpix_val_V_2_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_2_out_ap_vld),
    .outpix_val_V_5_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_5_out),
    .outpix_val_V_5_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_5_out_ap_vld),
    .outpix_val_V_8_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_8_out),
    .outpix_val_V_8_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_8_out_ap_vld),
    .outpix_val_V_11_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_11_out),
    .outpix_val_V_11_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_11_out_ap_vld),
    .luma_V_4_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_4_1_out),
    .luma_V_4_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_4_1_out_ap_vld),
    .luma_V_3_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_3_1_out),
    .luma_V_3_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_3_1_out_ap_vld),
    .luma_V_2_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_2_1_out),
    .luma_V_2_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_2_1_out_ap_vld),
    .luma_V_1_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_1_1_out),
    .luma_V_1_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_1_1_out_ap_vld),
    .luma_V_0_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_0_1_out),
    .luma_V_0_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_0_1_out_ap_vld),
    .inpix_val_V_11_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_11_1_out),
    .inpix_val_V_11_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_11_1_out_ap_vld),
    .inpix_val_V_10_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_10_1_out),
    .inpix_val_V_10_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_10_1_out_ap_vld),
    .inpix_val_V_9_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_9_1_out),
    .inpix_val_V_9_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_9_1_out_ap_vld),
    .inpix_val_V_8_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_8_1_out),
    .inpix_val_V_8_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_8_1_out_ap_vld),
    .inpix_val_V_7_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_7_1_out),
    .inpix_val_V_7_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_7_1_out_ap_vld),
    .inpix_val_V_6_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_6_1_out),
    .inpix_val_V_6_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_6_1_out_ap_vld),
    .inpix_val_V_5_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_5_1_out),
    .inpix_val_V_5_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_5_1_out_ap_vld),
    .inpix_val_V_4_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_4_1_out),
    .inpix_val_V_4_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_4_1_out_ap_vld),
    .inpix_val_V_3_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_3_1_out),
    .inpix_val_V_3_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_3_1_out_ap_vld),
    .inpix_val_V_2_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_2_1_out),
    .inpix_val_V_2_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_2_1_out_ap_vld),
    .inpix_val_V_1_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_1_1_out),
    .inpix_val_V_1_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_1_1_out_ap_vld),
    .inpix_val_V_0_1_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_0_1_out),
    .inpix_val_V_0_1_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_0_1_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln1049_fu_436_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1049_fu_436_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_start_reg <= 1'b1;
        end else if ((grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_ready == 1'b1)) begin
            grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        b_V_0_0_fu_170 <= 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        b_V_0_0_fu_170 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_10_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        g_V_0_0_fu_150 <= 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        g_V_0_0_fu_150 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_9_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        luma_V_0_0_fu_110 <= 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        luma_V_0_0_fu_110 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_0_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        r_V_0_0_fu_130 <= 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        r_V_0_0_fu_130 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_11_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_58 <= 16'd0;
    end else if (((icmp_ln1049_fu_436_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_58 <= y_2_fu_441_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        b_V_1_0729_fu_174 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_7_out;
        b_V_2_0730_fu_178 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_4_out;
        b_V_3_0731_fu_182 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_1_out;
        b_V_4_0732_fu_186 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_b_V_4_1_out;
        g_V_1_0725_fu_154 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_6_out;
        g_V_2_0726_fu_158 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_3_out;
        g_V_3_0727_fu_162 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_0_out;
        g_V_4_0728_fu_166 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_g_V_4_1_out;
        inpix_val_V_0_0705_fu_62 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_0_1_out;
        inpix_val_V_10_0715_fu_102 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_10_1_out;
        inpix_val_V_11_0716_fu_106 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_11_1_out;
        inpix_val_V_1_0706_fu_66 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_1_1_out;
        inpix_val_V_2_0707_fu_70 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_2_1_out;
        inpix_val_V_3_0708_fu_74 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_3_1_out;
        inpix_val_V_4_0709_fu_78 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_4_1_out;
        inpix_val_V_5_0710_fu_82 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_5_1_out;
        inpix_val_V_6_0711_fu_86 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_6_1_out;
        inpix_val_V_7_0712_fu_90 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_7_1_out;
        inpix_val_V_8_0713_fu_94 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_8_1_out;
        inpix_val_V_9_0714_fu_98 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_inpix_val_V_9_1_out;
        luma_V_1_0717_fu_114 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_1_1_out;
        luma_V_2_0718_fu_118 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_2_1_out;
        luma_V_3_0719_fu_122 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_3_1_out;
        luma_V_4_0720_fu_126 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_luma_V_4_1_out;
        r_V_1_0721_fu_134 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_8_out;
        r_V_2_0722_fu_138 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_5_out;
        r_V_3_0723_fu_142 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_outpix_val_V_2_out;
        r_V_4_0724_fu_146 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_r_V_4_1_out;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln1049_fu_436_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgRgb_read = grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_imgRgb_read;
    end else begin
        imgRgb_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgUnzip_write = grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_imgUnzip_write;
    end else begin
        imgUnzip_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1049_fu_436_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln1049_fu_436_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1051_fu_575_p2 = (zext_ln1035_fu_404_p1 + 17'd4);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_start = grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_ap_start_reg;

assign grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_empty = {{tmp_fu_580_p4}, {2'd0}};

assign icmp_ln1049_fu_436_p2 = ((y_fu_58 == height) ? 1'b1 : 1'b0);

assign imgUnzip_din = grp_ZipperRemoval_Pipeline_VITIS_LOOP_1051_2_fu_330_imgUnzip_din;

assign start_out = real_start;

assign tmp_fu_580_p4 = {{add_ln1051_fu_575_p2[16:2]}};

assign y_2_fu_441_p2 = (y_fu_58 + 16'd1);

assign zext_ln1035_fu_404_p1 = width;

endmodule //design_0_v_demosaic_0_0_ZipperRemoval
